ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk
-include $(PROJECT_ROOT)/roots.mk

define PINFO
PINFO DESCRIPTION=VIN libraries
endef

EXTRA_SILENT_VARIANTS = $(subst -, ,$(SECTION))
NAME =$(SECTION)

USEFILE = $(PROJECT_ROOT)/Usemsg

CCFLAGS += -Werror

#CCFLAGS += -DMAX96712_COLOR_PATTERN_TEST

EXTRA_INCVPATH+= $(INSTALL_ROOT_nto)/usr/include
EXTRA_INCVPATH+= $(INSTALL_ROOT_nto)/usr/include/hw

LIBS+= drvr

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk
