#ifndef R_IMPDRV_SETPMPOLICY_PCL_H
#define R_IMPDRV_SETPMPOLICY_PCL_H

#include "R_IMPDRV_SetPMPolicy.h"

static struct TEST_R_IMPDRV_SetPMPolicy_Pattern R_IMPDRV_SetPMPolicy_PCL[] =
{
	/* "Test Case ID             ", handle                  , *p_core_info       , core_type                  , core_num , policy                   , mutex_handle , mutex_time_period , resource_used , R_OSAL_ThsyncMutexLockForTimePeriod , R_OSAL_ThsyncMutexUnlock     , R_OSAL_IoDeviceOpen[2]                                                            , R_OSAL_PmSetPolicy                          , R_OSAL_PmSetRequiredState[2]                                     , R_OSAL_IoDeviceClose          }, { ercd                       ,  */
	/* R_IMPDRV_SetPMPolicy_0001 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_OK                } },
	/* R_IMPDRV_SetPMPolicy_0002 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_PG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_OK                } },
	/* R_IMPDRV_SetPMPolicy_0003 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_HP      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_OK                } },
	/* R_IMPDRV_SetPMPolicy_0004 */ { { TEST_ADDR_NULL          , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_ARGNULL        } },
	/* R_IMPDRV_SetPMPolicy_0005 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NULL     , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_ARGNULL        } },
	/* R_IMPDRV_SetPMPolicy_0006 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_INVALID , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PARAM          } },
	/* R_IMPDRV_SetPMPolicy_0007 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_INVALID , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PARAM          } },
	/* R_IMPDRV_SetPMPolicy_0008 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 8 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PARAM          } },
	/* R_IMPDRV_SetPMPolicy_0009 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_DTA     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_NOTSUPPORT     } },
	/* R_IMPDRV_SetPMPolicy_0010 */ { { TEST_ADDR_UNINIT_HANDLE , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SEQSTATE       } },
	/* R_IMPDRV_SetPMPolicy_0011 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_FAIL, TRUE }          , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0012 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_FAIL, TRUE }   , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0013 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_FAIL, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }  , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0014 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_FAIL, TRUE }                  , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0015 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_FAIL, OSAL_RETURN_OK }, TRUE  }                  , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0016 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_FAIL }, TRUE  }                  , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0017 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_FAIL, TRUE }    }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0018 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_DMAC    , 1 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_OK                } },
	/* R_IMPDRV_SetPMPolicy_0019 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_DMAC    , 1 }      , IMPDRV_PM_POLICY_PG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_OK                } },
	/* R_IMPDRV_SetPMPolicy_0020 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_DMAC    , 1 }      , IMPDRV_PM_POLICY_HP      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_OK                } },
	/* R_IMPDRV_SetPMPolicy_0021 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_PAR, TRUE }           , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0022 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_TIME, TRUE }          , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0023 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_BUSY, TRUE }          , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0024 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_HANDLE, TRUE }        , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0025 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_STATE, TRUE }         , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0026 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_HANDLE, TRUE } , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0027 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_STATE, TRUE }  , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0028 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_PAR, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }   , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0029 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_MEM, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }   , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0030 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_DEV, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }   , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0031 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_CONF, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }  , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0032 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_BUSY, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }  , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0033 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_ID, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0034 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_STATE, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  } , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0035 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_PAR, TRUE }                   , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0036 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_DEV, TRUE }                   , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0037 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_TIME, TRUE }                  , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0038 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_HANDLE, TRUE }                , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0039 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_STATE, TRUE }                 , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0040 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_UNSUPPORTED_OPERATION, TRUE } , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0041 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_PAR, OSAL_RETURN_OK }, TRUE  }                   , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0042 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_DEV, OSAL_RETURN_OK }, TRUE  }                   , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0043 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_TIME, OSAL_RETURN_OK }, TRUE  }                  , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0044 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_HANDLE, OSAL_RETURN_OK }, TRUE  }                , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0045 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_STATE, OSAL_RETURN_OK }, TRUE  }                 , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0046 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_UNSUPPORTED_OPERATION, OSAL_RETURN_OK }, TRUE  } , { OSAL_RETURN_OK, TRUE }      }, { IMPDRV_EC_NG_PMSYSTEMERROR  } },
	/* R_IMPDRV_SetPMPolicy_0047 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_DEV, TRUE }     }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0048 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_BUSY, TRUE }    }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0049 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_HANDLE, TRUE }  }, { IMPDRV_EC_NG_SYSTEMERROR    } },
	/* R_IMPDRV_SetPMPolicy_0050 */ { { TEST_ADDR_INIT_HANDLE   , TEST_ADDR_NOT_NULL , { IMPDRV_CORE_TYPE_IMP     , 0 }      , IMPDRV_PM_POLICY_CG      , { 1          , 1 }               , { 0 }         , { OSAL_RETURN_OK, TRUE }            , { OSAL_RETURN_OK, TRUE }     , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, { VALID_HANDLE, VALID_HANDLE } , TRUE  }    , { OSAL_RETURN_OK, TRUE }                    , { { OSAL_RETURN_OK, OSAL_RETURN_OK }, TRUE  }                    , { OSAL_RETURN_STATE, TRUE }   }, { IMPDRV_EC_NG_SYSTEMERROR    } }
};

#endif


