#ifndef R_PMA_FUNCTIONAL_TEST_ID_TBL_S4_H
#define R_PMA_FUNCTIONAL_TEST_ID_TBL_S4_H

#include "target/common/pma/hw/r_pma_hwa_id.h"
/*======================================================================================================================
Private global variables
======================================================================================================================*/
static e_pma_hwa_id_t g_pma_test_hwa_id[] = {
    /* S4 */
/*    R_PMA_HWA_ID_S4_CSDBGPAP             ,
    R_PMA_HWA_ID_S4_CR0                  ,
    R_PMA_HWA_ID_S4_DDR1_DDR0            ,
    R_PMA_HWA_ID_S4_I2C5                 ,
    R_PMA_HWA_ID_S4_I2C4                 ,
    R_PMA_HWA_ID_S4_I2C3                 ,
    R_PMA_HWA_ID_S4_I2C2                 ,
    R_PMA_HWA_ID_S4_I2C1                 ,
    R_PMA_HWA_ID_S4_I2C0                 ,
    R_PMA_HWA_ID_S4_HSCIF3               ,
    R_PMA_HWA_ID_S4_HSCIF2               ,
    R_PMA_HWA_ID_S4_HSCIF1               ,
    R_PMA_HWA_ID_S4_HSCIF0               ,*/
    R_PMA_HWA_ID_S4_RTDM1                ,
    R_PMA_HWA_ID_S4_RTDM0                ,/*
    R_PMA_HWA_ID_S4_RPC                  ,
    R_PMA_HWA_ID_S4_PCIE10               ,
    R_PMA_HWA_ID_S4_PCIE00               ,
    R_PMA_HWA_ID_S4_MSI3                 ,
    R_PMA_HWA_ID_S4_MSI2                 ,
    R_PMA_HWA_ID_S4_MSI1                 ,
    R_PMA_HWA_ID_S4_MSI0                 ,*/
    R_PMA_HWA_ID_S4_AES_ACC7             ,
    R_PMA_HWA_ID_S4_AES_ACC6             ,
    R_PMA_HWA_ID_S4_AES_ACC5             ,
    R_PMA_HWA_ID_S4_AES_ACC4             ,
    R_PMA_HWA_ID_S4_AES_ACC3             ,
    R_PMA_HWA_ID_S4_AES_ACC2             ,
    R_PMA_HWA_ID_S4_AES_ACC1             ,
    R_PMA_HWA_ID_S4_AES_ACC0             ,
    R_PMA_HWA_ID_S4_AES_ACC_WRAPPER      ,
    R_PMA_HWA_ID_S4_SHIP_S0              ,/*
    R_PMA_HWA_ID_S4_TMU4                 ,
    R_PMA_HWA_ID_S4_TMU3                 ,
    R_PMA_HWA_ID_S4_TMU2                 ,
    R_PMA_HWA_ID_S4_TMU1                 ,
    R_PMA_HWA_ID_S4_TMU0                 ,
    R_PMA_HWA_ID_S4_SYDM2                ,
    R_PMA_HWA_ID_S4_SYDM1                ,
    R_PMA_HWA_ID_S4_SDHI0                ,
    R_PMA_HWA_ID_S4_SDHI                 ,
    R_PMA_HWA_ID_S4_SCIF4                ,
    R_PMA_HWA_ID_S4_SCIF3                ,
    R_PMA_HWA_ID_S4_SCIF1                ,
    R_PMA_HWA_ID_S4_SCIF0                ,*/
    R_PMA_HWA_ID_S4_RTDM3                ,
    R_PMA_HWA_ID_S4_RTDM2                ,/*
    R_PMA_HWA_ID_S4_UCMT                 ,
    R_PMA_HWA_ID_S4_TSC4_TSC3_TSC2_TSC1  ,
    R_PMA_HWA_ID_S4_PFC0                 ,
    R_PMA_HWA_ID_S4_CMT3                 ,
    R_PMA_HWA_ID_S4_CMT2                 ,
    R_PMA_HWA_ID_S4_CMT1                 ,
    R_PMA_HWA_ID_S4_CMT0                 ,
    R_PMA_HWA_ID_S4_WDT1_WDT0            ,*/
    R_PMA_HWA_ID_S4_WCRC3                ,
    R_PMA_HWA_ID_S4_WCRC2                ,
    R_PMA_HWA_ID_S4_WCRC1                ,
    R_PMA_HWA_ID_S4_WCRC0                ,/*
    R_PMA_HWA_ID_S4_SWDT1_SWDT0          ,
    R_PMA_HWA_ID_S4_PCIE11               ,
    R_PMA_HWA_ID_S4_PCIE01               ,
    R_PMA_HWA_ID_S4_AULK2P               ,*/
    R_PMA_HWA_ID_S4_KCRC4                ,
    R_PMA_HWA_ID_S4_CRC3                 ,
    R_PMA_HWA_ID_S4_CRC2                 ,
    R_PMA_HWA_ID_S4_CRC1                 ,
    R_PMA_HWA_ID_S4_CRC0                 ,/*
    R_PMA_HWA_ID_S4_SCMT                 ,
    R_PMA_HWA_ID_S4_PFC0D3               ,
    R_PMA_HWA_ID_S4_PFC0D2               ,
    R_PMA_HWA_ID_S4_PFC0D1               ,
    R_PMA_HWA_ID_S4_WWDT9_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT8_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT7_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT6_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT5_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT4_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT3_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT2_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT1_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT0_RCLK           ,*/
    R_PMA_HWA_ID_S4_KCRC7                ,
    R_PMA_HWA_ID_S4_KCRC6                ,
    R_PMA_HWA_ID_S4_KCRC5                ,/*
    R_PMA_HWA_ID_S4_CKMMM                ,
    R_PMA_HWA_ID_S4_CKMPE0               ,
    R_PMA_HWA_ID_S4_CKMRT                ,
    R_PMA_HWA_ID_S4_CKM                  ,
    R_PMA_HWA_ID_S4_CKMHSC               ,
    R_PMA_HWA_ID_S4_CKMCR52              ,
    R_PMA_HWA_ID_S4_UFS                  ,*/
    R_PMA_HWA_ID_S4_SHIP_S2              ,
    R_PMA_HWA_ID_S4_SHIP_S1              ,/*
    R_PMA_HWA_ID_S4_ETHER_TSN_IF         ,
    R_PMA_HWA_ID_S4_R_SWITCH2            ,*/
    R_PMA_HWA_ID_S4_NUM                  
};

static e_pma_hwa_id_t g_pma_test_reset_hwa_id[] = {
    /* S4 */
/*    R_PMA_HWA_ID_S4_CSDBGPAP             ,
    R_PMA_HWA_ID_S4_CR0                  ,
    R_PMA_HWA_ID_S4_DDR1_DDR0            ,
    R_PMA_HWA_ID_S4_I2C5                 ,
    R_PMA_HWA_ID_S4_I2C4                 ,
    R_PMA_HWA_ID_S4_I2C3                 ,
    R_PMA_HWA_ID_S4_I2C2                 ,
    R_PMA_HWA_ID_S4_I2C1                 ,
    R_PMA_HWA_ID_S4_I2C0                 ,
    R_PMA_HWA_ID_S4_HSCIF3               ,
    R_PMA_HWA_ID_S4_HSCIF2               ,
    R_PMA_HWA_ID_S4_HSCIF1               ,
    R_PMA_HWA_ID_S4_HSCIF0               ,*/
    R_PMA_HWA_ID_S4_RTDM1                ,
    R_PMA_HWA_ID_S4_RTDM0                ,/*
    R_PMA_HWA_ID_S4_RPC                  ,
    R_PMA_HWA_ID_S4_PCIE10               ,
    R_PMA_HWA_ID_S4_PCIE00               ,
    R_PMA_HWA_ID_S4_MSI3                 ,
    R_PMA_HWA_ID_S4_MSI2                 ,
    R_PMA_HWA_ID_S4_MSI1                 ,
    R_PMA_HWA_ID_S4_MSI0                 ,*/
    R_PMA_HWA_ID_S4_AES_ACC7             ,
    R_PMA_HWA_ID_S4_AES_ACC6             ,
    R_PMA_HWA_ID_S4_AES_ACC5             ,
    R_PMA_HWA_ID_S4_AES_ACC4             ,
    R_PMA_HWA_ID_S4_AES_ACC3             ,
    R_PMA_HWA_ID_S4_AES_ACC2             ,
    R_PMA_HWA_ID_S4_AES_ACC1             ,
    R_PMA_HWA_ID_S4_AES_ACC0             ,
    R_PMA_HWA_ID_S4_AES_ACC_WRAPPER      ,
    R_PMA_HWA_ID_S4_SHIP_S0              ,/*
    R_PMA_HWA_ID_S4_TMU4                 ,
    R_PMA_HWA_ID_S4_TMU3                 ,
    R_PMA_HWA_ID_S4_TMU2                 ,
    R_PMA_HWA_ID_S4_TMU1                 ,
    R_PMA_HWA_ID_S4_TMU0                 ,
    R_PMA_HWA_ID_S4_SYDM2                ,
    R_PMA_HWA_ID_S4_SYDM1                ,
    R_PMA_HWA_ID_S4_SDHI0                ,
    R_PMA_HWA_ID_S4_SDHI                 ,
    R_PMA_HWA_ID_S4_SCIF4                ,
    R_PMA_HWA_ID_S4_SCIF3                ,
    R_PMA_HWA_ID_S4_SCIF1                ,
    R_PMA_HWA_ID_S4_SCIF0                ,*/
    R_PMA_HWA_ID_S4_RTDM3                ,
    R_PMA_HWA_ID_S4_RTDM2                ,/*
    R_PMA_HWA_ID_S4_UCMT                 ,
    R_PMA_HWA_ID_S4_TSC4_TSC3_TSC2_TSC1  ,
    R_PMA_HWA_ID_S4_PFC0                 ,
    R_PMA_HWA_ID_S4_CMT3                 ,
    R_PMA_HWA_ID_S4_CMT2                 ,
    R_PMA_HWA_ID_S4_CMT1                 ,
    R_PMA_HWA_ID_S4_CMT0                 ,
    R_PMA_HWA_ID_S4_WDT1_WDT0            ,*/
    R_PMA_HWA_ID_S4_WCRC3                ,
    R_PMA_HWA_ID_S4_WCRC2                ,
    R_PMA_HWA_ID_S4_WCRC1                ,
    R_PMA_HWA_ID_S4_WCRC0                ,/*
    R_PMA_HWA_ID_S4_SWDT1_SWDT0          ,
    R_PMA_HWA_ID_S4_PCIE11               ,
    R_PMA_HWA_ID_S4_PCIE01               ,
    R_PMA_HWA_ID_S4_AULK2P               ,*/
    R_PMA_HWA_ID_S4_KCRC4                ,
    R_PMA_HWA_ID_S4_CRC3                 ,
    R_PMA_HWA_ID_S4_CRC2                 ,
    R_PMA_HWA_ID_S4_CRC1                 ,
    R_PMA_HWA_ID_S4_CRC0                 ,/*
    R_PMA_HWA_ID_S4_SCMT                 ,
    R_PMA_HWA_ID_S4_PFC0D3               ,
    R_PMA_HWA_ID_S4_PFC0D2               ,
    R_PMA_HWA_ID_S4_PFC0D1               ,
    R_PMA_HWA_ID_S4_WWDT9_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT8_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT7_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT6_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT5_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT4_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT3_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT2_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT1_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT0_RCLK           ,*/
    R_PMA_HWA_ID_S4_KCRC7                ,
    R_PMA_HWA_ID_S4_KCRC6                ,
    R_PMA_HWA_ID_S4_KCRC5                ,/*
    R_PMA_HWA_ID_S4_CKMMM                ,
    R_PMA_HWA_ID_S4_CKMPE0               ,
    R_PMA_HWA_ID_S4_CKMRT                ,
    R_PMA_HWA_ID_S4_CKM                  ,
    R_PMA_HWA_ID_S4_CKMHSC               ,
    R_PMA_HWA_ID_S4_CKMCR52              ,
    R_PMA_HWA_ID_S4_UFS                  ,*/
    R_PMA_HWA_ID_S4_SHIP_S2              ,
    R_PMA_HWA_ID_S4_SHIP_S1              ,/*
    R_PMA_HWA_ID_S4_ETHER_TSN_IF         ,
    R_PMA_HWA_ID_S4_R_SWITCH2            ,*/
    R_PMA_HWA_ID_S4_NUM                  
};

static e_pma_hwa_id_t g_pma_test_reset_hwa_id_reverse[] = {
    /* S4 */
/*    R_PMA_HWA_ID_S4_CSDBGPAP             ,
    R_PMA_HWA_ID_S4_CR0                  ,
    R_PMA_HWA_ID_S4_DDR1_DDR0            ,
    R_PMA_HWA_ID_S4_I2C5                 ,
    R_PMA_HWA_ID_S4_I2C4                 ,
    R_PMA_HWA_ID_S4_I2C3                 ,
    R_PMA_HWA_ID_S4_I2C2                 ,
    R_PMA_HWA_ID_S4_I2C1                 ,
    R_PMA_HWA_ID_S4_I2C0                 ,
    R_PMA_HWA_ID_S4_HSCIF3               ,
    R_PMA_HWA_ID_S4_HSCIF2               ,
    R_PMA_HWA_ID_S4_HSCIF1               ,
    R_PMA_HWA_ID_S4_HSCIF0               ,*/
    R_PMA_HWA_ID_S4_RTDM1                ,
    R_PMA_HWA_ID_S4_RTDM0                ,/*
    R_PMA_HWA_ID_S4_RPC                  ,
    R_PMA_HWA_ID_S4_PCIE10               ,
    R_PMA_HWA_ID_S4_PCIE00               ,
    R_PMA_HWA_ID_S4_MSI3                 ,
    R_PMA_HWA_ID_S4_MSI2                 ,
    R_PMA_HWA_ID_S4_MSI1                 ,
    R_PMA_HWA_ID_S4_MSI0                 ,*/
    R_PMA_HWA_ID_S4_AES_ACC7             ,
    R_PMA_HWA_ID_S4_AES_ACC6             ,
    R_PMA_HWA_ID_S4_AES_ACC5             ,
    R_PMA_HWA_ID_S4_AES_ACC4             ,
    R_PMA_HWA_ID_S4_AES_ACC3             ,
    R_PMA_HWA_ID_S4_AES_ACC2             ,
    R_PMA_HWA_ID_S4_AES_ACC1             ,
    R_PMA_HWA_ID_S4_AES_ACC0             ,
    R_PMA_HWA_ID_S4_AES_ACC_WRAPPER      ,
    R_PMA_HWA_ID_S4_SHIP_S0              ,/*
    R_PMA_HWA_ID_S4_TMU4                 ,
    R_PMA_HWA_ID_S4_TMU3                 ,
    R_PMA_HWA_ID_S4_TMU2                 ,
    R_PMA_HWA_ID_S4_TMU1                 ,
    R_PMA_HWA_ID_S4_TMU0                 ,
    R_PMA_HWA_ID_S4_SYDM2                ,
    R_PMA_HWA_ID_S4_SYDM1                ,
    R_PMA_HWA_ID_S4_SDHI0                ,
    R_PMA_HWA_ID_S4_SDHI                 ,
    R_PMA_HWA_ID_S4_SCIF4                ,
    R_PMA_HWA_ID_S4_SCIF3                ,
    R_PMA_HWA_ID_S4_SCIF1                ,
    R_PMA_HWA_ID_S4_SCIF0                ,*/
    R_PMA_HWA_ID_S4_RTDM3                ,
    R_PMA_HWA_ID_S4_RTDM2                ,/*
    R_PMA_HWA_ID_S4_UCMT                 ,
    R_PMA_HWA_ID_S4_TSC4_TSC3_TSC2_TSC1  ,
    R_PMA_HWA_ID_S4_PFC0                 ,
    R_PMA_HWA_ID_S4_CMT3                 ,
    R_PMA_HWA_ID_S4_CMT2                 ,
    R_PMA_HWA_ID_S4_CMT1                 ,
    R_PMA_HWA_ID_S4_CMT0                 ,
    R_PMA_HWA_ID_S4_WDT1_WDT0            ,*/
    R_PMA_HWA_ID_S4_WCRC3                ,
    R_PMA_HWA_ID_S4_WCRC2                ,
    R_PMA_HWA_ID_S4_WCRC1                ,
    R_PMA_HWA_ID_S4_WCRC0                ,/*
    R_PMA_HWA_ID_S4_SWDT1_SWDT0          ,
    R_PMA_HWA_ID_S4_PCIE11               ,
    R_PMA_HWA_ID_S4_PCIE01               ,
    R_PMA_HWA_ID_S4_AULK2P               ,*/
    R_PMA_HWA_ID_S4_KCRC4                ,
    R_PMA_HWA_ID_S4_CRC3                 ,
    R_PMA_HWA_ID_S4_CRC2                 ,
    R_PMA_HWA_ID_S4_CRC1                 ,
    R_PMA_HWA_ID_S4_CRC0                 ,/*
    R_PMA_HWA_ID_S4_SCMT                 ,
    R_PMA_HWA_ID_S4_PFC0D3               ,
    R_PMA_HWA_ID_S4_PFC0D2               ,
    R_PMA_HWA_ID_S4_PFC0D1               ,
    R_PMA_HWA_ID_S4_WWDT9_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT8_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT7_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT6_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT5_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT4_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT3_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT2_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT1_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT0_RCLK           ,*/
    R_PMA_HWA_ID_S4_KCRC7                ,
    R_PMA_HWA_ID_S4_KCRC6                ,
    R_PMA_HWA_ID_S4_KCRC5                ,/*
    R_PMA_HWA_ID_S4_CKMMM                ,
    R_PMA_HWA_ID_S4_CKMPE0               ,
    R_PMA_HWA_ID_S4_CKMRT                ,
    R_PMA_HWA_ID_S4_CKM                  ,
    R_PMA_HWA_ID_S4_CKMHSC               ,
    R_PMA_HWA_ID_S4_CKMCR52              ,
    R_PMA_HWA_ID_S4_UFS                  ,*/
    R_PMA_HWA_ID_S4_SHIP_S2              ,
    R_PMA_HWA_ID_S4_SHIP_S1              ,/*
    R_PMA_HWA_ID_S4_ETHER_TSN_IF         ,
    R_PMA_HWA_ID_S4_R_SWITCH2            ,*/
    R_PMA_HWA_ID_S4_NUM                  
};

static e_pma_hwa_id_t g_pma_test_no_sysc_hwa_id[] = {
    /* S4 */
/*    R_PMA_HWA_ID_S4_CSDBGPAP             ,
    R_PMA_HWA_ID_S4_CR0                  ,
    R_PMA_HWA_ID_S4_DDR1_DDR0            ,
    R_PMA_HWA_ID_S4_I2C5                 ,
    R_PMA_HWA_ID_S4_I2C4                 ,
    R_PMA_HWA_ID_S4_I2C3                 ,
    R_PMA_HWA_ID_S4_I2C2                 ,
    R_PMA_HWA_ID_S4_I2C1                 ,
    R_PMA_HWA_ID_S4_I2C0                 ,
    R_PMA_HWA_ID_S4_HSCIF3               ,
    R_PMA_HWA_ID_S4_HSCIF2               ,
    R_PMA_HWA_ID_S4_HSCIF1               ,
    R_PMA_HWA_ID_S4_HSCIF0               ,*/
    R_PMA_HWA_ID_S4_RTDM1                ,
    R_PMA_HWA_ID_S4_RTDM0                ,/*
    R_PMA_HWA_ID_S4_RPC                  ,
    R_PMA_HWA_ID_S4_PCIE10               ,
    R_PMA_HWA_ID_S4_PCIE00               ,
    R_PMA_HWA_ID_S4_MSI3                 ,
    R_PMA_HWA_ID_S4_MSI2                 ,
    R_PMA_HWA_ID_S4_MSI1                 ,
    R_PMA_HWA_ID_S4_MSI0                 ,*/
    R_PMA_HWA_ID_S4_AES_ACC7             ,
    R_PMA_HWA_ID_S4_AES_ACC6             ,
    R_PMA_HWA_ID_S4_AES_ACC5             ,
    R_PMA_HWA_ID_S4_AES_ACC4             ,
    R_PMA_HWA_ID_S4_AES_ACC3             ,
    R_PMA_HWA_ID_S4_AES_ACC2             ,
    R_PMA_HWA_ID_S4_AES_ACC1             ,
    R_PMA_HWA_ID_S4_AES_ACC0             ,
    R_PMA_HWA_ID_S4_AES_ACC_WRAPPER      ,
    R_PMA_HWA_ID_S4_SHIP_S0              ,/*
    R_PMA_HWA_ID_S4_TMU4                 ,
    R_PMA_HWA_ID_S4_TMU3                 ,
    R_PMA_HWA_ID_S4_TMU2                 ,
    R_PMA_HWA_ID_S4_TMU1                 ,
    R_PMA_HWA_ID_S4_TMU0                 ,
    R_PMA_HWA_ID_S4_SYDM2                ,
    R_PMA_HWA_ID_S4_SYDM1                ,
    R_PMA_HWA_ID_S4_SDHI0                ,
    R_PMA_HWA_ID_S4_SDHI                 ,
    R_PMA_HWA_ID_S4_SCIF4                ,
    R_PMA_HWA_ID_S4_SCIF3                ,
    R_PMA_HWA_ID_S4_SCIF1                ,
    R_PMA_HWA_ID_S4_SCIF0                ,*/
    R_PMA_HWA_ID_S4_RTDM3                ,
    R_PMA_HWA_ID_S4_RTDM2                ,/*
    R_PMA_HWA_ID_S4_UCMT                 ,
    R_PMA_HWA_ID_S4_TSC4_TSC3_TSC2_TSC1  ,
    R_PMA_HWA_ID_S4_PFC0                 ,
    R_PMA_HWA_ID_S4_CMT3                 ,
    R_PMA_HWA_ID_S4_CMT2                 ,
    R_PMA_HWA_ID_S4_CMT1                 ,
    R_PMA_HWA_ID_S4_CMT0                 ,
    R_PMA_HWA_ID_S4_WDT1_WDT0            ,*/
    R_PMA_HWA_ID_S4_WCRC3                ,
    R_PMA_HWA_ID_S4_WCRC2                ,
    R_PMA_HWA_ID_S4_WCRC1                ,
    R_PMA_HWA_ID_S4_WCRC0                ,/*
    R_PMA_HWA_ID_S4_SWDT1_SWDT0          ,
    R_PMA_HWA_ID_S4_PCIE11               ,
    R_PMA_HWA_ID_S4_PCIE01               ,
    R_PMA_HWA_ID_S4_AULK2P               ,*/
    R_PMA_HWA_ID_S4_KCRC4                ,
    R_PMA_HWA_ID_S4_CRC3                 ,
    R_PMA_HWA_ID_S4_CRC2                 ,
    R_PMA_HWA_ID_S4_CRC1                 ,
    R_PMA_HWA_ID_S4_CRC0                 ,/*
    R_PMA_HWA_ID_S4_SCMT                 ,
    R_PMA_HWA_ID_S4_PFC0D3               ,
    R_PMA_HWA_ID_S4_PFC0D2               ,
    R_PMA_HWA_ID_S4_PFC0D1               ,
    R_PMA_HWA_ID_S4_WWDT9_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT8_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT7_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT6_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT5_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT4_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT3_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT2_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT1_RCLK           ,
    R_PMA_HWA_ID_S4_WWDT0_RCLK           ,*/
    R_PMA_HWA_ID_S4_KCRC7                ,
    R_PMA_HWA_ID_S4_KCRC6                ,
    R_PMA_HWA_ID_S4_KCRC5                ,/*
    R_PMA_HWA_ID_S4_CKMMM                ,
    R_PMA_HWA_ID_S4_CKMPE0               ,
    R_PMA_HWA_ID_S4_CKMRT                ,
    R_PMA_HWA_ID_S4_CKM                  ,
    R_PMA_HWA_ID_S4_CKMHSC               ,
    R_PMA_HWA_ID_S4_CKMCR52              ,
    R_PMA_HWA_ID_S4_UFS                  ,*/
    R_PMA_HWA_ID_S4_SHIP_S2              ,
    R_PMA_HWA_ID_S4_SHIP_S1              ,/*
    R_PMA_HWA_ID_S4_ETHER_TSN_IF         ,
    R_PMA_HWA_ID_S4_R_SWITCH2            ,*/
    R_PMA_HWA_ID_S4_NUM                  
};

#endif  /* R_PMA_FUNCTIONAL_TEST_ID_TBL_S4_H */
