/*
* $QNXLicenseC:
* Copyright 2020, QNX Software Systems.
* Copyright 2021, Renesas Electronics Corporation.
*
* Licensed under the Apache License, Version 2.0 (the "License"). You
* may not reproduce, modify or distribute this software except in
* compliance with the License. You may obtain a copy of the License
* at: http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OF ANY KIND, either express or implied.
*
* This file may contain contributions from others, either as
* contributors under the License or as licensors under other terms.
* Please review this entire file for other proprietary rights or license
* notices, as well as the QNX Development Suite License Guide at
* http://licensing.qnx.com/license-guide/ for other information.
* $
*/
#ifndef _FLEXRAY_REGS_H
#define _FLEXRAY_REGS_H

/* Operation registers */
#define FROC                   (0x0004)
#define FR_OC_OE                (0)
#define FR_OC_BEC               (1)
#define FR_OC_OEP               (7)
#define FR_OC_T0IE              (16)
#define FR_OC_T1IE              (17)
#define FR_OC_T2IE              (18)

#define FROS                   (0x000C)
#define FR_OS_OS                (0)
#define FR_OS_TIS_MASK          (0x07)
#define FR_OS_T0IS              (16)
#define FR_OS_T1IS              (17)
#define FR_OS_T2IS              (18)

/* Special registers */
#define FRLCK                  (0x001C)
    #define FR_LCK_CLK_L        (0)
    #define FR_LCK_CLK_H        (7)
    #define FR_LCK_CLK_FIRST_WRITE          (0xCE)
    #define FR_LCK_CLK_SECOND_WRITE         (0x31)

/* Interrupt registers */
#define FREIR                  (0x0020)
	#define FR_EIR_CLEAR_ALL    (0x07070FFF)
	#define FR_EIR_SET_ALL    	(0x07070FFF)
	#define FR_EIR_ENABLE    	(0x07070FC0)
    #define FR_EIR_PEMC         (0)
    #define FR_EIR_CNA          (1)
    #define FR_EIR_SFBM         (2)
    #define FR_EIR_SFO          (3)
    #define FR_EIR_CCF          (4)
    #define FR_EIR_CCL          (5)
    #define FR_EIR_AERR         (6)
    #define FR_EIR_RFO          (7)
    #define FR_EIR_EFA          (8)
    #define FR_EIR_IIBA         (9)
    #define FR_EIR_IOBA         (10)
    #define FR_EIR_MHF          (11)
    #define FR_EIR_EDA          (16)
    #define FR_EIR_LTVA         (17)
    #define FR_EIR_TABA         (18)
    #define FR_EIR_EDB          (24)
    #define FR_EIR_LTVB         (25)
    #define FR_EIR_TABB         (26)
#define FRSIR                  (0x0024)
	#define FR_SIR_CLEAR_ALL    (0x0303FFFF)
	#define FR_SIR_TI_MASK   	(0x03)
    #define FR_SIR_WST          (0)
    #define FR_SIR_CAS          (1)
    #define FR_SIR_CYCS         (2)
    #define FR_SIR_TXI          (3)
    #define FR_SIR_RXI          (4)
    #define FR_SIR_RFNE         (5)
    #define FR_SIR_RFCL         (6)
    #define FR_SIR_NMVC         (7)
    #define FR_SIR_TI0          (8)
    #define FR_SIR_TI1          (9)
    #define FR_SIR_TIBC         (10)
    #define FR_SIR_TOBC         (11)
    #define FR_SIR_SWE          (12)
    #define FR_SIR_SUCS         (13)
    #define FR_SIR_MBSI         (14)
    #define FR_SIR_SDS          (15)
    #define FR_SIR_WUPA         (16)
    #define FR_SIR_MTSA         (17)
    #define FR_SIR_WUPB         (24)
    #define FR_SIR_MTSB         (25)
#define FREILS                 (0x0028)
    #define FR_EILS_PEMCL       (0)
    #define FR_EILS_CNAL        (1)
    #define FR_EILS_SFBML       (2)
    #define FR_EILS_SFOL        (3)
    #define FR_EILS_CCFL        (4)
    #define FR_EILS_CCLL        (5)
    #define FR_EILS_AERRL       (6)
    #define FR_EILS_RFOL        (7)
    #define FR_EILS_EFAL        (8)
    #define FR_EILS_IIBAL       (9)
    #define FR_EILS_IOBAL       (10)
    #define FR_EILS_MHFL        (11)
    #define FR_EILS_EDAL        (16)
    #define FR_EILS_LTVAL       (17)
    #define FR_EILS_TABAL       (18)
    #define FR_EILS_EDBL        (24)
    #define FR_EILS_LTVBL       (25)
    #define FR_EILS_TABBL       (26)
#define FRSILS                 (0x002C)
    #define FR_SILS_WSTL        (0)
    #define FR_SILS_CASL        (1)
    #define FR_SILS_CYCSL       (2)
    #define FR_SILS_TXIL        (3)
    #define FR_SILS_RXIL        (4)
    #define FR_SILS_RFNEL       (5)
    #define FR_SILS_RFCLL       (6)
    #define FR_SILS_NMVCL       (7)
    #define FR_SILS_TI0L        (8)
    #define FR_SILS_TI1L        (9)
    #define FR_SILS_TIBCL       (10)
    #define FR_SILS_TOBCL       (11)
    #define FR_SILS_SWEL        (12)
    #define FR_SILS_SUCSL       (13)
    #define FR_SILS_MBSIL       (14)
    #define FR_SILS_SDSL        (15)
    #define FR_SILS_WUPAL       (16)
    #define FR_SILS_MTSAL       (17)
    #define FR_SILS_WUPBL       (24)
    #define FR_SILS_MTSBL       (25)
	#define FR_SILS_LINE1		\
		FR_SILS_WSTL | FR_SILS_CASL	| FR_SILS_CYCSL |			\
		FR_SILS_TXIL | FR_SILS_RXIL | FR_SILS_RFNEL	|			\
		FR_SILS_RFCLL | FR_SILS_NMVCL | FR_SILS_TI0L |			\
		FR_SILS_TI1L | FR_SILS_TIBCL | FR_SILS_TOBCL |			\
		FR_SILS_SWEL | FR_SILS_SUCSL | FR_SILS_MBSIL |			\
		FR_SILS_SDSL | FR_SILS_WUPAL | FR_SILS_MTSAL |			\
		FR_SILS_WUPBL | FR_SILS_MTSBL	

#define FREIES                 (0x0030)
    #define FR_EIES_PEMCE       (0)
    #define FR_EIES_CNAE        (1)
    #define FR_EIES_SFBME       (2)
    #define FR_EIES_SFOE        (3)
    #define FR_EIES_CCFE        (4)
    #define FR_EIES_CCLE        (5)
    #define FR_EIES_AERRE       (6)
    #define FR_EIES_RFOE        (7)
    #define FR_EIES_EFAE        (8)
    #define FR_EIES_IIBAE       (9)
    #define FR_EIES_IOBAE       (10)
    #define FR_EIES_MHFE        (11)
    #define FR_EIES_EDAE        (16)
    #define FR_EIES_LTVAE       (17)
    #define FR_EIES_TABAE       (18)
    #define FR_EIES_EDBE        (24)
    #define FR_EIES_LTVBE       (25)
    #define FR_EIES_TABBE       (26)
#define FREIER                 (0x0034)
	#define FR_EIER_CLEAR_ALL   (0x07070FFF)
    #define FR_EIER_PEMCD       (0)
    #define FR_EIER_CNAD        (1)
    #define FR_EIER_SFBMD       (2)
    #define FR_EIER_SFOD        (3)
    #define FR_EIER_CCFD        (4)
    #define FR_EIER_CCLD        (5)
    #define FR_EIER_AERRD       (6)
    #define FR_EIER_RFOD        (7)
    #define FR_EIER_EFAD        (8)
    #define FR_EIER_IIBAD       (9)
    #define FR_EIER_IOBAD       (10)
    #define FR_EIER_MHFD        (11)
    #define FR_EIER_EDAD        (16)
    #define FR_EIER_LTVAD       (17)
    #define FR_EIER_TABAD       (18)
    #define FR_EIER_EDBD        (24)
    #define FR_EIER_LTVBD       (25)
    #define FR_EIER_TABBD       (26)
#define FRSIES                  (0x0038)
	#define FR_FRSIES_SET_ALL   (0x0303FCFF)
	#define FR_FRSIES_ENABLE    (0x00000470)
    #define FR_SIES_WSTE        (0)
    #define FR_SIES_CASE        (1)
    #define FR_SIES_CYCSE       (2)
    #define FR_SIES_TXIE        (3)
    #define FR_SIES_RXIE        (4)
    #define FR_SIES_RFNEE       (5)
    #define FR_SIES_RFCLE       (6)
    #define FR_SIES_NMVCE       (7)
    #define FR_SIES_TI0E        (8)
    #define FR_SIES_TI1E        (9)
    #define FR_SIES_TIBCE       (10)
    #define FR_SIES_TOBCE       (11)
    #define FR_SIES_SWEE        (12)
    #define FR_SIES_SUCSE       (13)
    #define FR_SIES_MBSIE       (14)
    #define FR_SIES_SDSE        (15)
    #define FR_SIES_WUPAE       (16)
    #define FR_SIES_MTSAE       (17)
    #define FR_SIES_WUPBE       (24)
    #define FR_SIES_MTSBE       (25)
#define FRSIER                 (0x003C)
	// #define FR_SIER_CLEAR_ALL   (0x0303FFFF)
	#define FR_SIER_CLEAR_ALL   (0x0000037F)
    #define FR_SIER_WSTD        (0)
    #define FR_SIER_CASD        (1)
    #define FR_SIER_CYCSD       (2)
    #define FR_SIER_TXID        (3)
    #define FR_SIER_RXID        (4)
    #define FR_SIER_RFNED       (5)
    #define FR_SIER_RFCLD       (6)
    #define FR_SIER_NMVCD       (7)
    #define FR_SIER_TI0D        (8)
    #define FR_SIER_TI1D        (9)
    #define FR_SIER_TIBCD       (10)
    #define FR_SIER_TOBCD       (11)
    #define FR_SIER_SWED        (12)
    #define FR_SIER_SUCSD       (13)
    #define FR_SIER_MBSID       (14)
    #define FR_SIER_SDSD        (15)
    #define FR_SIER_WUPAD       (16)
    #define FR_SIER_MTSAD       (17)
    #define FR_SIER_WUPBD       (24)
    #define FR_SIER_MTSBD       (25)
#define FRILE                  (0x0040)
    #define FR_ILE_EINT0        (0)
    #define FR_ILE_EINT1        (1)
    #define FR_ILE_EINT01       (3)
/* Timer registers*/
#define FRT0C                  (0x0044)
    #define FR_FRTC_TMO_L      (16)
	#define FR_FRTC_TMO_H      (29)
	#define FR_FRTC_TMC_L      (16)
	#define FR_FRTC_TMC_H      (29)
	#define FR_FRTC_TCC_L      (8)
	#define FR_FRTC_TCC_H      (14)
	#define FR_FRTC_TMS      	(1)
	#define FR_FRTC_TRC      	(0)
	#define	FR_TOCC_MASK		(0x7F)	
	#define	FR_TMO_MASK			(0x3FFF)
	#define	FR_TMC_MASK			(0x3FFF)	
#define FRT1C                  (0x0048)
#define FRT2C                  (0x0844)
#define FRSTPW1                (0x004C)
    #define FR_STPW1_ESWT        (0)
    #define FR_STPW1_SWMS        (1)
    #define FR_STPW1_EDGE        (2)
    #define FR_STPW1_SSWT        (3)
    #define FR_STPW1_EINT0       (5)
    #define FR_STPW1_EINT1       (6)
    #define FR_STPW1_SCCV_L      (8)
    #define FR_STPW1_SCCV_H      (13)
    #define FR_STPW1_SMTV_L      (16)
    #define FR_STPW1_SMTV_H      (29)
#define FRSTPW2                (0x0050)
    #define FR_STPW2_SSCVA_L      (0)
    #define FR_STPW2_SSCVA_H      (10)
    #define FR_STPW2_SSCVB_L      (16)
    #define FR_STPW2_SSCVB_H      (26)
/* CC Control registers */
#define FRSUCC1                (0x0080)
    #define FR_SUCC1_CMD_L          (0)
    #define FR_SUCC1_CMD_H          (3)
	#define FR_SUCC1_CMD_MASK		(0xF << 0)
        #define FR_SUCC1_CMD_NOT_ACCEPTED               (0x00)
        #define FR_SUCC1_CMD_CONFIG                     (0x01)
        #define FR_SUCC1_CMD_READY                      (0x02)
        #define FR_SUCC1_CMD_WAKEUP                     (0x03)
        #define FR_SUCC1_CMD_RUN                        (0x04)
        #define FR_SUCC1_CMD_ALL_SLOTS                  (0x05)
        #define FR_SUCC1_CMD_HALT                       (0x06)
        #define FR_SUCC1_CMD_FREEZE                     (0x07)
        #define FR_SUCC1_CMD_SEND_MTS                   (0x08)
        #define FR_SUCC1_CMD_ALLOW_COLD_START           (0x09)
        #define FR_SUCC1_CMD_RESET_STATUS_INDICATORS    (0x0A)
        #define FR_SUCC1_CMD_CLEAR_RAMS                 (0x0c)
    #define FR_SUCC1_PBSY       (7)
    #define FR_SUCC1_TXST       (8)
    #define FR_SUCC1_TXSY       (9)
    #define FR_SUCC1_CSA_L      (11)
    #define FR_SUCC1_CSA_H      (15)
        #define FR_CSA_MIN      (2)
        #define FR_CSA_MAX      (31)
    #define FR_SUCC1_PTA_L      (16)
    #define FR_SUCC1_PTA_H      (20)
        #define FR_PTA_MIN      (0)
        #define FR_PTA_MAX      (31)
    #define FR_SUCC1_WUCS       (21)
    #define FR_SUCC1_TSM        (22)
    #define FR_SUCC1_HCSE       (23)
    #define FR_SUCC1_MTSA       (24)
    #define FR_SUCC1_MTSB       (25)
    #define FR_SUCC1_CCHA       (26)
    #define FR_SUCC1_CCHB       (27)

#define FRSUCC2                (0x0084)
    #define FR_SUCC2_LT_L       (0)
    #define FR_SUCC2_LT_H       (20)
        #define FR_LT_MIN       (1284)
        #define FR_LT_MAX       (1283846)
        #define FR_LTN_MIN      (2)
        #define FR_LTN_MAX      (16)
    #define FR_SUCC2_LTN_L      (24)
    #define FR_SUCC2_LTN_H      (27)
    
#define FRSUCC3                (0x0088)
    #define FR_SUCC3_WCP_L      (0)
    #define FR_SUCC3_WCP_H      (3)
        #define FR_WCP_MIN      (1)
        #define FR_WCP_MAX      (15)
        #define FR_WCF_MIN      (1)
        #define FR_WCF_MAX      (15)
    #define FR_SUCC3_WCF_L      (4)
    #define FR_SUCC3_WCF_H      (7)

#define FRNEMC                 (0x008C)
    #define FR_NEMC_NML_L       (0)
    #define FR_NEMC_NML_H       (3)
        #define FR_NML_MIN      (0)
        #define FR_NML_MAX      (12)

#define FRPRTC1                (0x0090)
    #define FR_PRTC1_TSST_L      (0)
    #define FR_PRTC1_TSST_H      (3)
        #define FR_TSST_MIN      (3)
        #define FR_TSST_MAX      (15)
    #define FR_PRTC1_CASM_L      (4)
    #define FR_PRTC1_CASM_H      (10)
        #define FR_CASM_MIN      (67)
        #define FR_CASM_MAX      (99)
    #define FR_PRTC1_SPP_L       (12)
    #define FR_PRTC1_SPP_H       (13)
    #define FR_PRTC1_BRP_L       (14)
    #define FR_PRTC1_BRP_H       (15)
        #define FR_BRP_10_MBIT   (0)
        #define FR_BRP_5_MBIT    (1)
        #define FR_BRP_2_5_MBIT  (2)
    #define FR_PRTC1_RXW_L       (16)
    #define FR_PRTC1_RXW_H       (24)
        #define FR_RXW_MIN       (76)
        #define FR_RXW_MAX       (301)
    #define FR_PRTC1_RWP_L       (26)
    #define FR_PRTC1_RWP_H       (31)
        #define FR_RWP_MIN       (2)
        #define FR_RWP_MAX       (63)

#define FRPRTC2                (0x0094)
    #define FR_PRTC2_RXI_L      (0)
    #define FR_PRTC2_RXI_H      (5)
        #define FR_RXI_MIN      (14)
        #define FR_RXI_MAX      (59)
    #define FR_PRTC2_RXL_L      (8)
    #define FR_PRTC2_RXL_H      (13)
        #define FR_RXL_MIN      (10)
        #define FR_RXL_MAX      (55)
    #define FR_PRTC2_TXI_L      (16)
    #define FR_PRTC2_TXI_H      (23)
        #define FR_TXI_MIN      (45)
        #define FR_TXI_MAX      (180)
    #define FR_PRTC2_TXL_L      (24)
    #define FR_PRTC2_TXL_H      (29)
        #define FR_TXL_MIN      (15)
        #define FR_TXL_MAX      (60)

#define FRMHDC                 (0x0098)
    #define FR_MHDC_SFDL_L      (0)
    #define FR_MHDC_SFDL_H      (6)
        #define FR_SFDL_MIN     (0)
        #define FR_SFDL_MAX     (127)
    #define FR_MHDC_SLT_L       (16)
    #define FR_MHDC_SLT_H       (28)
        #define FR_SLT_MIN      (0)
        #define FR_SLT_MAX      (7981)

#define FRGTUC1                (0x00A0)
    #define FR_GTUC1_UT_L       (0)
    #define FR_GTUC1_UT_H       (19)
        #define FR_UT_MIN      (640)
        #define FR_UT_MAX      (640000)

#define FRGTUC2                (0x00A4)
    #define FR_GTUC2_MPC_L      (0)
    #define FR_GTUC2_MPC_H      (13)
        #define FR_MPC_MIN      (10)
        #define FR_MPC_MAX      (16000)
    #define FR_GTUC2_SNM_L      (16)
    #define FR_GTUC2_SNM_H      (19)
        #define FR_SNM_MIN      (2)
        #define FR_SNM_MAX      (15)

#define FRGTUC3                (0x00A8)
    #define FR_GTUC3_UIOA_L     (0)
    #define FR_GTUC3_UIOA_H     (7)
        #define FR_UIOA_MIN     (0)
        #define FR_UIOA_MAX     (240)
    #define FR_GTUC3_UIOB_L     (8)
    #define FR_GTUC3_UIOB_H     (15)
        #define FR_UIOB_MIN     (0)
        #define FR_UIOB_MAX     (240)
    #define FR_GTUC3_MIOA_L     (16)
    #define FR_GTUC3_MIOA_H     (22)
        #define FR_MIOA_MIN     (2)
        #define FR_MIOA_MAX     (72)
    #define FR_GTUC3_MIOB_L     (24)
    #define FR_GTUC3_MIOB_H     (30)
        #define FR_MIOB_MIN     (2)
        #define FR_MIOB_MAX     (72)

#define FRGTUC4                (0x00AC)
    #define FR_GTUC4_NIT_L      (0)
    #define FR_GTUC4_NIT_H      (13)
        #define FR_NIT_MIN      (7)
        #define FR_NIT_MAX      (15997)
    #define FR_GTUC4_OCS_L      (16)
    #define FR_GTUC4_OCS_H      (29)
        #define FR_OCS_MIN      (8)
        #define FR_OCS_MAX      (15998)

#define FRGTUC5                (0x00B0)
    #define FR_GTUC5_DCA_L      (0)
    #define FR_GTUC5_DCA_H      (7)
        #define FR_DCA_MAX      (200)
    #define FR_GTUC5_DCB_L      (8)
    #define FR_GTUC5_DCB_H      (15)
        #define FR_DCB_MAX      (200)
    #define FR_GTUC5_CDD_L      (16)
    #define FR_GTUC5_CDD_H      (20)
        #define FR_CDD_MAX      (20)
    #define FR_GTUC5_DEC_L      (24)
    #define FR_GTUC5_DEC_H      (31)
        #define FR_DEC_MIN      (14)
        #define FR_DEC_MAX      (143)

#define FRGTUC6                (0x00B4)
    #define FR_GTUC6_ASR_L      (0)
    #define FR_GTUC6_ASR_H      (10)
        #define FR_ASR_MAX      (1875)
    #define FR_GTUC6_MOD_L      (16)
    #define FR_GTUC6_MOD_H      (26)
        #define FR_MOD_MIN      (2)
        #define FR_MOD_MAX      (1923)
    
#define FRGTUC7                (0x00B8)
    #define FR_GTUC7_SSL_L      (0)
    #define FR_GTUC7_SSL_H      (9)
        #define FR_SSL_MIN      (4)
        #define FR_SSL_MAX      (659)
    #define FR_GTUC7_NSS_L      (16)
    #define FR_GTUC7_NSS_H      (25)
        #define FR_NSS_MIN      (2)
        #define FR_NSS_MAX      (1023)

#define FRGTUC8                (0x00BC)
    #define FR_GTUC8_MSL_L      (0)
    #define FR_GTUC8_MSL_H      (5)
        #define FR_MSL_MIN      (2)
        #define FR_MSL_MAX      (63)
    #define FR_GTUC8_NMS_L      (16)
    #define FR_GTUC8_NMS_H      (28)
        #define FR_NMS_MAX      (7986)

#define FRGTUC9                (0x00C0)
    #define FR_GTUC9_APO_L      (0)
    #define FR_GTUC9_APO_H      (5)
        #define FR_APO_MIN      (1)
        #define FR_APO_MAX      (63)
    #define FR_GTUC9_MAPO_L     (8)
    #define FR_GTUC9_MAPO_H     (12)
        #define FR_MAPO_MIN     (1)
        #define FR_MAPO_MAX     (31)
    #define FR_GTUC9_DSI_L      (16)
    #define FR_GTUC9_DSI_H      (17)
        #define FR_DSI_MAX      (2)

#define FRGTUC10               (0x00C4)
    #define FR_GTUC10_MOC_L     (0)
    #define FR_GTUC10_MOC_H     (13)
        #define FR_MOC_MIN      (5)
        #define FR_MOC_MAX      (15266)
    #define FR_GTUC10_MRC_L     (16)
    #define FR_GTUC10_MRC_H     (26)
        #define FR_MRC_MIN      (2)
        #define FR_MRC_MAX      (1923)

#define FRGTUC11               (0x00C8)
    #define FR_GTUC11_EOCC_L    (0)
    #define FR_GTUC11_EOCC_H    (1)
        #define FR_EOCC_NO_EXT_OFF_CORRECTION       (0)
        #define FR_EOCC_SUB                         (2)
        #define FR_EOCC_ADD                         (3)
    #define FR_GTUC11_ERCC_L    (8)
    #define FR_GTUC11_ERCC_H    (9)
        #define FR_ERCC_NO_EXT_RATE_CORRECTION      (0)
        #define FR_ERCC_SUB                         (2)
        #define FR_ERCC_ADD                         (3)
    #define FR_GTUC11_EOC_L     (16)
    #define FR_GTUC11_EOC_H     (18)
        #define FR_EOC_MAX      (7)
    #define FR_GTUC11_ERC_L     (24)
    #define FR_GTUC11_ERC_H     (26)
        #define FR_ERC_MAX      (7)

/* CC Status Registers */
#define FRCCSV                 (0x0100)
	#define FR_CCSV_POCS_MASK	(0x3f << 0)
    #define FR_CCSV_POCS_L      (0)
    #define FR_CCSV_POCS_H      (5)
    #define FR_CCSV_FSI         (6)
    #define FR_CCSV_HRQ         (7)
    #define FR_CCSV_SLM_L       (8)
    #define FR_CCSV_SLM_H       (9)
    #define FR_CCSV_CSNI        (12)
    #define FR_CCSV_CSAI        (13)
    #define FR_CCSV_CSI         (14)
    #define FR_CCSV_WSV_L       (16)
    #define FR_CCSV_WSV_H       (18)
        #define FR_CCSV_WSV_UNDEFINED               (0)
        #define FR_CCSV_WSV_RECEIVED_HEADER         (1)
        #define FR_CCSV_WSV_RECEIVED_WUP            (2)
        #define FR_CCSV_WSV_COLLISION_HEADER        (3)
        #define FR_CCSV_WSV_COLLISION_WUP           (4)
        #define FR_CCSV_WSV_COLLISION_UNKNOWN       (5)
        #define FR_CCSV_WSV_TRANSMITTED             (6)
    #define FR_CCSV_RCA_L       (19)
    #define FR_CCSV_RCA_H       (23)
    #define FR_CCSV_PSL_L       (24)
    #define FR_CCSV_PSL_H       (29)
#define FRCCEV                 (0x0104)
    #define FR_CCEV_CCFC_L      (0)
    #define FR_CCEV_CCFC_H      (3)
    #define FR_CCEV_ERRM_L      (6)
    #define FR_CCEV_ERRM_H      (7)
        #define FR_CCEV_ERRM_ACTIVE         (0)
        #define FR_CCEV_ERRM_PASSIVE        (1)
        #define FR_CCEV_ERRM_COMMHALT       (2)
    #define FR_CCEV_PTAC_L      (8)
    #define FR_CCEV_PTAC_H      (12)
#define FRSCV                  (0x0110)
#define FRMTCCV                (0x0114)
	#define FRMTCCV_CCV_MASK	(0x3F<16) 
	#define FRMTCCV_MTV_MASK	(0x3FFF)	
#define FRRCV                  (0x0118)
#define FROCV                  (0x011C)
#define FRSFS                  (0x0120)
#define FRSWNIT                (0x0124)
#define FRACS                  (0x0128)

#define FRESID(n)             ((((n) >= (1)) && ((n) <= (15))) ? (0x0130 + 0x04*(n - 1)) : (0x0130))
#define FROSID(n)             ((((n) >= (1)) && ((n) <= (15))) ? (0x0170 + 0x04*(n - 1)) : (0x0170))
#define FRNMV(n)              ((((n) >= (1)) && ((n) <= (3))) ? (0x01B0 + 0x04*(n - 1)) : (0x01B0))

/* Message Buffer Control registers */
#define FRMRC                  (0x0300)
    #define FR_MRC_FDB_L        (0)
    #define FR_MRC_FDB_H        (7)
    #define FR_MRC_FFB_L        (8)
    #define FR_MRC_FFB_H        (15)
    #define FR_MRC_LCB_L        (16)
    #define FR_MRC_LCB_H        (23)
    #define FR_MRC_SEC_L        (24)
    #define FR_MRC_SEC_H        (25)
    #define FR_MRC_SPLM         (26)
    #define FR_MRC_SEC_UNLOCKED   				0
    #define FR_MRC_SEC_STATIC_FIFO_LOCKED		1
    #define FR_MRC_SEC_LOCKED					2
    #define FR_MRC_SEC_LOCKED_LIMIT_TX			3	
#define FRFRF                  (0x0304)
    #define FR_FRF_CH_L         (0)
    #define FR_FRF_CH_H         (1)
    #define FR_FRF_FID_L        (2)
    #define FR_FRF_FID_H        (12)
    #define FR_FRF_CYF_L        (16)
    #define FR_FRF_CYF_H        (22)
    #define FR_FRF_RSS          (23)
    #define FR_FRF_RNF          (24)
#define FRFRFM                 (0x0308)
    #define FR_FRFM_MFID_L      (2)
    #define FR_FRFM_MFID_H      (12)
#define FRFCL                  (0x030C)
    #define FR_FCL_CL_L         (0)
    #define FR_FCL_CL_H         (7)

/* Message Buffer Status registers */
#define FRMHDS                 (0x0310)
	#define FR_MHDS_CLEAR_ALL   (0x0000007C)
    #define FR_MHDS_AMR         (2)
    #define FR_MHDS_ATBF1       (3)
    #define FR_MHDS_ATBF2       (4)
    #define FR_MHDS_FMBD        (5)
    #define FR_MHDS_MFMB        (6)
	#define FR_MHDS_ERR			((1<<FR_MHDS_AMR)|(1<<FR_MHDS_ATBF1)|(1<<FR_MHDS_ATBF2)|(1<<FR_MHDS_FMBD)|(1<<FR_MHDS_MFMB))
    #define FR_MHDS_CRAM        (7)
    #define FR_MHDS_FMB_L       (8)
    #define FR_MHDS_FMB_H       (14)
    #define FR_MHDS_MBT_L       (16)
    #define FR_MHDS_MBT_H       (22)
    #define FR_MHDS_MBU_L       (24)
    #define FR_MHDS_MBU_H       (30)
#define FRLDTS                 (0x0314)
#define FRFSR                  (0x0318)
	#define FR_FSR_RFNE			(0)
	#define FR_FSR_RFCL			(1)
	#define FR_FSR_RFO			(2)
	#define FR_FSR_RFFL_L		(8)
	#define FR_FSR_RFFL_H		(15)
	#define FR_FSR_RFFL_MASK	(0xFF)
#define FRMHDF                 (0x031C)
#define FRTXRQ(i)              (((i) >= (0)) && ((i) <= (3)) ? (0x0320 + 0x04*i) : (0x0320))
#define FRNDAT(i)              (((i) >= (0)) && ((i) <= (3)) ? (0x0330 + 0x04*i) : (0x0330))
#define FRMBSC(i)              (((i) >= (0)) && ((i) <= (3)) ? (0x0340 + 0x04*i) : (0x0340))

/* Input Buffer */
#define FRWRDS(n)              (((n) >= (1)) && ((n) <= (64)) ? (0x0400 + 0x04*(n - 1)) : (0x0400))
#define FRWRHS1                (0x0500)
    #define FR_WRHS1_FID_L      (0)
    #define FR_WRHS1_FID_H      (10)
    #define FR_WRHS1_CYC_L      (16)
    #define FR_WRHS1_CYC_H      (22)
        #define FR_WRHS1_CYC_MAX    (0x7F)
    #define FR_WRHS1_CH_L       (24)
    #define FR_WRHS1_CH_H       (25)
        #define FR_WRHS1_CH_NEITHER     (0)
        #define FR_WRHS1_CH_A           (1)
        #define FR_WRHS1_CH_B           (2)
        #define FR_WRHS1_CH_BOTH        (3)
    #define FR_WRHS1_CFG        (26)
    #define FR_WRHS1_PPIT       (27)
    #define FR_WRHS1_TXM        (28)
        #define FR_WRHS1_TXM_CONTINUOUS    (0)
        #define FR_WRHS1_TXM_SINGLE        (1)
    #define FR_WRHS1_MBI        (29)

#define FRWRHS2                (0x0504)
    #define FR_WRHS2_CRC_L      (0)
    #define FR_WRHS2_CRC_H      (10)
	#define FR_WRHS2_CRC_MASK   (0x7FF)
    #define FR_WRHS2_PLC_L      (16)
    #define FR_WRHS2_PLC_H      (22)
    #define FR_WRHS2_PLC_MAX    (0x7F)

#define FRWRHS3                (0x0508)
    #define FR_WRHS3_DP_L       (0)
    #define FR_WRHS3_DP_H       (10)
    #define FR_WRHS3_DP_MASK    (0x7FF)
#define FRIBCM                 (0x0510)
    #define FR_IBCM_LHSH        (0)
    #define FR_IBCM_LDSH        (1)
    #define FR_IBCM_STXRH       (2)
    #define FR_IBCM_LHSS        (16)
    #define FR_IBCM_LDSS        (17)
    #define FR_IBCM_STXRS       (18)
#define FRIBCR                 (0x0514)
	#define FR_IBCR_IBRS_MASK   (0x7F<<16)
	#define FR_IBCR_IBRH_MASK   (0x7F)
    #define FR_IBCR_IBRH_L      (0)
    #define FR_IBCR_IBRH_H      (6)
    #define FR_IBCR_IBSYH       (15)
    #define FR_IBCR_IBRS_L      (16)
    #define FR_IBCR_IBRS_H      (22)
    #define FR_IBCR_IBSYS       (31)

/* Output Buffer */
#define FRRDDS(n)              (((n) >= (1)) && ((n) <= (64)) ? (0x0600 + 0x04*(n - 1)) : (0x0600))
#define FRRDHS1                (0x0700)
    #define FR_RDHS1_FID_L      (0)
    #define FR_RDHS1_FID_H      (10)
	#define FR_RDHS1_FID_MASK   (0x7FF)
    #define FR_RDHS1_CYC_L      (16)
    #define FR_RDHS1_CYC_H      (22)
    #define FR_RDHS1_CYC_MASK   (0x7F)	
    #define FR_RDHS1_CH_L       (24)
    #define FR_RDHS1_CH_H       (25)
	#define FR_RDHS1_CH_MASK    (0x03)
    #define FR_RDHS1_CFG        (26)
    #define FR_RDHS1_PPIT       (27)
    #define FR_RDHS1_TXM        (28)
    #define FR_RDHS1_MBI        (29)
	
#define FRRDHS2                (0x0704)
    #define FR_RDHS2_CRC_L      (0)
    #define FR_RDHS2_CRC_H      (10)
    #define FR_RDHS2_CRC_MASK   (0x7FF)	
    #define FR_RDHS2_PLC_L      (16)
    #define FR_RDHS2_PLC_H      (22)
    #define FR_RDHS2_PLR_L      (24)
    #define FR_RDHS2_PLR_H      (30)
	#define FR_RDHS_PLC_MASK    (0x7F)
#define FRRDHS3                (0x0708)
    #define FR_RDHS3_DP_L       (0)
    #define FR_RDHS3_DP_H       (10)
    #define FR_RDHS3_RCC_L      (16)
    #define FR_RDHS3_RCC_H      (21)
	#define FR_RDHS3_RCC_MASK   (0x3F)
	#define FR_RDHS3_RCI        (24)
	#define FR_RDHS3_SFI        (25)
	#define FR_RDHS3_SYN        (26)
	#define FR_RDHS3_NFI        (27)
	#define FR_RDHS3_PPI        (28)
	#define FR_RDHS3_RES        (29)
	#define FR_RDHS3_MASK_ONE   (0x01)
#define FRMBS                  (0x070C)
#define FROBCM                 (0x0710)
    #define FR_OBCM_RHSS        (0)
    #define FR_OBCM_RDSS        (1)
    #define FR_OBCM_RHSH        (16)
    #define FR_OBCM_RDSH        (17)
#define FROBCR                 (0x0714)
    #define FR_OBCR_OBRS_L      (0)
    #define FR_OBCR_OBRS_H      (6)
    #define FR_OBCR_OBRS_MASK   (0x7F)	
    #define FR_OBCR_VIEW        (8)
    #define FR_OBCR_REQ         (9)
    #define FR_OBCR_OBSYS       (15)
    #define FR_OBCR_OBRH_L      (16)
    #define FR_OBCR_OBRH_H      (22)

/* Data Transfer Control registers */
#define FRITC                  (0x0800)
    #define FR_ITC_ITE          (0)
    #define FR_ITC_IQHR         (1)
    #define FR_ITC_IQFIE        (8)
    #define FR_ITC_IQEIE        (9)
    #define FR_ITC_ITM_L        (16)
    #define FR_ITC_ITM_H        (22)
    #define FR_ITC_ITM_MAX      (0x7F)
#define FROTC                  (0x0804)
    #define FR_OTC_OTE          (0)
    #define FR_OTC_OTCS         (1)
    #define FR_OTC_OIE          (8)
    #define FR_OTC_FIE          (9)
    #define FR_OTC_OWIE         (10)
    #define FR_OTC_FWIE         (11)
    #define FR_OTC_FTM_L        (16)
    #define FR_OTC_FTM_H        (20)
#define FRIBA                  (0x0808)
    #define FR_IBA_ITA_L        (0)
    #define FR_IBA_ITA_H        (31)
#define FRFBA                  (0x080C)
    #define FR_FBA_FTA_L        (0)
    #define FR_FBA_FTA_H        (31)
#define FROBA                  (0x0810)
    #define FR_OBA_OTA_L        (2)
    #define FR_OBA_OTA_H        (31)
#define FRIQC                  (0x0814)
    #define FR_IQC_IMBNR_L      (0)
    #define FR_IQC_IMBNR_H      (6)
#define FRUIR                  (0x0818)
	#define FR_UIR_UIDX_L		(0)
	#define FR_UIR_UIDX_H		(7)
#define FRUOR                  (0x081C)
	#define FR_UOR_UMBNR_L      (0)
	#define FR_UOR_UMBNR_H      (6)
	#define FR_UOR_URDS         (9)

    #define FR_WRHS4_IMBNR_L    (0)
    #define FR_WRHS4_IMBNR_H    (6)
    #define FR_WRHS4_LHS        (8)
    #define FR_WRHS4_LDS        (9)
    #define FR_WRHS4_STR        (10)
    #define FR_WRHS4_INV        (11)
    #define FR_WRHS4_DSL_L      (16)
    #define FR_WRHS4_DSL_H      (22)
/* Data Transfer Status registers */
#define FRITS                  (0x0820)
    #define FR_ITS_ITS          (0)
    #define FR_ITS_IQH          (1)
    #define FR_ITS_UIRP         (2)
    #define FR_ITS_IQFIS        (8)
    #define FR_ITS_IQEIS        (9)
    #define FR_ITS_IQFP         (12)
    #define FR_ITS_IPIDX_L      (16)
    #define FR_ITS_IPIDX_H      (22)
	#define FR_ITS_IPIDX_MASK   (0x7F)
    #define FR_ITS_IGIDX_L      (24)
    #define FR_ITS_IGIDX_H      (30)
#define FROTS                  (0x0824)
    #define FR_OTS_OTS              (0)
    #define FR_OTS_UORP             (2)
    #define FR_OTS_OTIS             (8)
    #define FR_OTS_FIS              (9)
    #define FR_OTS_OWIS             (10)
    #define FR_OTS_FWIS             (11)
    #define FR_OTS_FDA              (13)
    #define FR_OTS_OWP              (14)
    #define FR_OTS_FWP              (15)
    #define FR_OTS_FGIDX_L          (16)
    #define FR_OTS_FGIDX_H          (20)
	#define FR_OTS_FGIDX_MASK       (0x1F)
    #define FR_OTS_FFL_L            (24)
    #define FR_OTS_FFL_H            (29)
	#define FR_OTS_FFL_MASK         (0x3F)
#define FRAES                  (0x0828)
    #define FR_AES_EIDX_L           (0)
	#define FR_AES_EIDX_H           (7)
	#define FR_AES_EIDX_MASK		(0xFF)
	#define FR_AES_IAE           	(8)
	#define FR_AES_OAE           	(9)	
	#define FR_AES_FAE           	(10)
	#define FR_AES_MAE           	(11)
#define FRAEA                  (0x082C)
#define FRDA(i)                (((i) >= (0)) && ((i) <= (3)) ? (0x0830 + 0x04*(i)) : (0x0830))

#endif
