/**
 * @file osal_test.h
 * @brief OSAL test application process header file.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <libgen.h>
#include "rcar-xos/osal/r_osal.h"

#ifndef OSAL_TEST_H
#define OSAL_TEST_H

/* Define */
#define OSAL_TEST_ALL_EXEC (100)
#define OSAL_TEST_APP_EXIT (999)

#define OSAL_TEST_OK (0)
#define OSAL_TEST_NG (1)

/* enum */
/* OSAL Manager ID */
typedef enum
{
	OSAL_TEST_THREAD          = 1,
	OSAL_TEST_SYNCHRONIZATION,
	OSAL_TEST_MESSAGE,
	OSAL_TEST_CLOCK_TIME,
	OSAL_TEST_INTERRUPT,
	OSAL_TEST_IO,
	OSAL_TEST_PM,
	OSAL_TEST_MEMORY,
	OSAL_TEST_COMMON_FUNCTION,
	OSAL_TEST_ALL             = OSAL_TEST_ALL_EXEC,
	OSAL_TEST_EXIT            = OSAL_TEST_APP_EXIT,
	OSAL_TEST_PARENT_MAX      = OSAL_TEST_COMMON_FUNCTION,
} OSAL_TEST_PARENT_ID;

/* OSAL Manager API ID */
typedef enum
{
/* OSAL Thread Manager */
	OSAL_TEST_THREADCREATE = 1,
	OSAL_TEST_THREADSLEEPUNTILTIMESTAMP,
	OSAL_TEST_THREADSLEEPFORTIMEPERIOD,
	OSAL_TEST_THREADSELF,
	OSAL_TEST_THREADEQUAL,
	OSAL_TEST_THREADJOIN,
	OSAL_TEST_THREADINITIALIZETHREADCONFIGST,

/* OSAL Synchronization Manager */
	OSAL_TEST_THSYNCMUTEXCREATE = 1,
	OSAL_TEST_THSYNCMUTEXDESTROY,
	OSAL_TEST_THSYNCMUTEXLOCKFORTIMEPERIOD,
	OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,
	OSAL_TEST_THSYNCMUTEXTRYLOCK,
	OSAL_TEST_THSYNCMUTEXUNLOCK,
	OSAL_TEST_THSYNCCONDCREATE,
	OSAL_TEST_THSYNCCONDDESTROY,
	OSAL_TEST_THSYNCCONDWAITFORTIMEPERIOD,
	OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,
	OSAL_TEST_THSYNCCONDBROADCAST,
	OSAL_TEST_THSYNCCONDSIGNAL,
	OSAL_TEST_THSYNCMEMORYBARRIER,

/* OSAL Message Manager */
	OSAL_TEST_MQCREATE = 1,
	OSAL_TEST_MQDELETE,
	OSAL_TEST_MQSENDUNTILTIMESTAMP,
	OSAL_TEST_MQSENDFORTIMEPERIOD,
	OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,
	OSAL_TEST_MQRECEIVEFORTIMEPERIOD,
	OSAL_TEST_MQISFULL,
	OSAL_TEST_MQISEMPTY,
	OSAL_TEST_MQGETCONFIG,
	OSAL_TEST_MQRESET,
	OSAL_TEST_MQINITIALIZEMQCONFIGST,

/* OSAL Clock&Time Manager */
	OSAL_TEST_CLOCKTIMEGETTIMESTAMP = 1,
	OSAL_TEST_CLOCKTIMECALCULATETIMEDIFFERENCE,

/* OSAL Interrupt Manager */
	OSAL_TEST_INTERRUPTGETNUMOFIRQCHANNELS = 1,
	OSAL_TEST_INTERRUPTREGISTERISR,
	OSAL_TEST_INTERRUPTUNREGISTERISR,
	OSAL_TEST_INTERRUPTENABLEISR,
	OSAL_TEST_INTERRUPTDISABLEISR,
	OSAL_TEST_INTERRUPTSETISRPRIORITY,
	OSAL_TEST_INTERRUPTISISRCONTEXT,

/* OSAL IO Manager */
	OSAL_TEST_IOGETNUMOFDEVICES = 1,
	OSAL_TEST_IOGETDEVICELIST,
	OSAL_TEST_IODEVICEOPEN,
	OSAL_TEST_IODEVICECLOSE,
	OSAL_TEST_IOREAD8,
	OSAL_TEST_IOREAD16,
	OSAL_TEST_IOREAD32,
	OSAL_TEST_IOREAD64,
	OSAL_TEST_IOBLOCKREAD8,
	OSAL_TEST_IOBLOCKREAD16,
	OSAL_TEST_IOBLOCKREAD32,
	OSAL_TEST_IOBLOCKREAD64,
	OSAL_TEST_IOWRITE8,
	OSAL_TEST_IOWRITE16,
	OSAL_TEST_IOWRITE32,
	OSAL_TEST_IOWRITE64,
	OSAL_TEST_IOBLOCKWRITE8,
	OSAL_TEST_IOBLOCKWRITE16,
	OSAL_TEST_IOBLOCKWRITE32,
	OSAL_TEST_IOBLOCKWRITE64,
	OSAL_TEST_IOGETAXIBUSIDFROMDEVICENAME,
	OSAL_TEST_IOGETAXIBUSNAME,
	OSAL_TEST_IOGETAXIBUSNAMELIST,
	OSAL_TEST_IOGETDEVICEAXIBUSID,
	OSAL_TEST_IOGETAXIIDLISTFORAXIBUSNAME,
	OSAL_TEST_IOGETAXIIDLISTFORDEVICEHDL,
	OSAL_TEST_IOGETAXIIDLISTFORDEVICENAME,
	OSAL_TEST_IOGETNUMOFAXIIDSFORAXIBUSNAME,
	OSAL_TEST_IOGETNUMOFAXIIDSFORDEVICEHDL,
	OSAL_TEST_IOGETNUMOFAXIIDSFORDEVICENAME,

/* OSAL PM Manager */
	OSAL_TEST_PMSETREQUIREDSTATE = 1,
	OSAL_TEST_PMGETREQUIREDSTATE,
	OSAL_TEST_PMWAITFORSTATE,
	OSAL_TEST_PMGETSTATE,
	OSAL_TEST_PMSETPOLICY,
	OSAL_TEST_PMGETPOLICY,
	OSAL_TEST_PMSETRESETSTATE,
	OSAL_TEST_PMGETRESETSTATE,
	OSAL_TEST_PMSETPOSTCLOCK,
	OSAL_TEST_PMGETLOWESTINTERMEDIATEPOWERSTATE,

/* OSAL Memory Manager */
	OSAL_TEST_MMNGROPEN = 1,
	OSAL_TEST_MMNGROPENFROMREGIONIDX,
	OSAL_TEST_MMNGRCLOSE,
	OSAL_TEST_MMNGRALLOC,
	OSAL_TEST_MMNGRDEALLOC,
	OSAL_TEST_MMNGRGETCONFIG,
	OSAL_TEST_MMNGRGETOSALMAXCONFIG,
	OSAL_TEST_MMNGRGETOSALMAXCONFIGFROMREGIONIDX,
	OSAL_TEST_MMNGRINITIALIZEMMNGRCONFIGST,
	OSAL_TEST_MMNGRREGISTERMONITOR,
	OSAL_TEST_MMNGRGETCPUPTR,
	OSAL_TEST_MMNGRGETCONSTCPUPTR,
	OSAL_TEST_MMNGRFLUSH,
	OSAL_TEST_MMNGRINVALIDATE,
	OSAL_TEST_MMNGRGETHWADDR,
	OSAL_TEST_MMNGRGETSIZE,
	OSAL_TEST_MMNGRCHECKBUFFER,
	OSAL_TEST_MMNGRDEBUGMMNGRPRINT,
	OSAL_TEST_MMNGRDEBUGBUFFERPRINT,
	OSAL_TEST_MMNGRINITIALIZEMEMORYMANAGEROBJ,
	OSAL_TEST_MMNGRINITIALIZEMEMORYBUFFEROBJ,

/* OSAL Common Function */
	OSAL_TEST_INITIALIZE = 1,
	OSAL_TEST_DEINITIALIZE,
	OSAL_TEST_GETVERSION,

/* Maximum ID of Manager */
	OSAL_TEST_THREAD_MAX     = OSAL_TEST_THREADINITIALIZETHREADCONFIGST,
	OSAL_TEST_THREADSYNC_MAX = OSAL_TEST_THSYNCMEMORYBARRIER,
	OSAL_TEST_MQ_MAX         = OSAL_TEST_MQINITIALIZEMQCONFIGST,
	OSAL_TEST_CLOCKTIME_MAX  = OSAL_TEST_CLOCKTIMECALCULATETIMEDIFFERENCE,
	OSAL_TEST_INTERRUPT_MAX  = OSAL_TEST_INTERRUPTISISRCONTEXT,
	OSAL_TEST_IO_MAX         = OSAL_TEST_IOGETNUMOFAXIIDSFORDEVICENAME,
	OSAL_TEST_PM_MAX         = OSAL_TEST_PMGETLOWESTINTERMEDIATEPOWERSTATE,
	OSAL_TEST_MEMORY_MAX     = OSAL_TEST_MMNGRINITIALIZEMEMORYBUFFEROBJ,
	OSAL_TEST_COMMON_MAX     = OSAL_TEST_GETVERSION,
} OSAL_TEST_API_ID;

/* OSAL test ID */
typedef enum
{
	OSAL_TEST_ID001 = 1,
	OSAL_TEST_ID002,
	OSAL_TEST_ID003,
	OSAL_TEST_ID004,
	OSAL_TEST_ID005,
	OSAL_TEST_ID006,
	OSAL_TEST_ID007,
	OSAL_TEST_ID008,
	OSAL_TEST_ID009,
	OSAL_TEST_ID010,
	OSAL_TEST_ID011,
	OSAL_TEST_ID012,
	OSAL_TEST_ID013,
	OSAL_TEST_ID014,
	OSAL_TEST_ID015,
	OSAL_TEST_ID016,
	OSAL_TEST_ID017,
	OSAL_TEST_ID018,
	OSAL_TEST_ID019,
	OSAL_TEST_ID020,
	OSAL_TEST_ID021,
	OSAL_TEST_ID022,
	OSAL_TEST_ID023,
	OSAL_TEST_ID024,
	OSAL_TEST_ID025,
	OSAL_TEST_ID026,
	OSAL_TEST_ID027,
	OSAL_TEST_ID028,
	OSAL_TEST_ID029,
	OSAL_TEST_ID030,
	OSAL_TEST_ID031,
	OSAL_TEST_ID032,
	OSAL_TEST_ID033,
	OSAL_TEST_ID034,
	OSAL_TEST_ID035,
	OSAL_TEST_MAX = OSAL_TEST_ID035,
} OSAL_TEST_ID;

/* struct */
/* expect data structure */
typedef struct {
	OSAL_TEST_PARENT_ID	parent_id;
	OSAL_TEST_API_ID	api_id;
	OSAL_TEST_ID		test_id;
	e_osal_return_t		expect;
} osal_test_expect_data_t;

extern bool init_flag;

extern uint32_t			test_pass;
extern uint32_t			test_fail;
extern uint32_t			test_skip;
extern int				test_err;

/* Macro */
/* ErrorLog output macro */
#define OSAL_TEST_ERR(fmt, ...) \
	fprintf(stderr, \
			"error: [%s][%s][line.%d] %02d_%03d_%03d: " fmt "\n", \
			__FILE__, __func__, __LINE__, __VA_ARGS__); \
    test_err = -1;

/* Additional information create macro for output of evaluation results. */
#define OSAL_TEST_MAKE_INFO(opt_info, exp_str, ret_str) \
	sprintf(opt_info, "Expectation value: %s, Return value: %s", exp_str, ret_str)

/* Information related to state */
#define OSAL_TEST_GET_INFO(opt_info, x, exp_str) \
	sprintf(opt_info,"%s %s",x, exp_str); \
	printf("%s\n", opt_info)

int osal_test(int parent_number, int child_number);

#endif
