ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk
-include $(PROJECT_ROOT)/roots.mk
#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../../../install
   USE_INSTALL_ROOT=1
##############################################################
define PINFO
PINFO DESCRIPTION=BUS MONITOR libraries
endef

EXTRA_INCVPATH += $(PROJECT_ROOT)/../../../../../../install/usr/include
EXTRA_LIBVPATH += $(PROJECT_ROOT)/../../../../../../install/aarch64le/lib

EXTRA_SILENT_VARIANTS = $(subst -, ,$(SECTION))
NAME = libcrc

LIBS += dma-rcar-sysdmac drvr smmu c

#########################################################
# Make sure the build environment is configured properly
#########################################################
include $(MKFILES_ROOT)/qtargets.mk
##########################################################
# Install our binaries/headers into the CPP shared folder
##########################################################
