ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

define PINFO
PINFO DESCRIPTION=R-Car CMM Resource Manager
endef

LDFLAGS += -Wl,-E

INSTALLDIR=sbin
USEFILE = $(PROJECT_ROOT)/Usemsg
NAME=rcar-cmm

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk
