ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk
-include $(PROJECT_ROOT)/roots.mk

define PINFO
PINFO DESCRIPTION=CMM test program
endef

NAME=cmm_test
USEFILE = $(PROJECT_ROOT)/Usemsg
INSTALLDIR = /usr/bin

EXTRA_INCVPATH += $(PROJECT_ROOT)/sample_filter

include $(MKFILES_ROOT)/qtargets.mk

CCFLAGS+=-Wall
LIBS+=screen img

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../install
   USE_INSTALL_ROOT=1
##############################################################
