#ifndef _DEFAULT_SOURCE
/* PRQA S 0603,3214,0602 1 # This definition is required to use glibc. */
#define _DEFAULT_SOURCE
#endif
#include <errno.h>
#include <libgen.h>
#include <arpa/inet.h>
#include <assert.h>
#include <sys/syscall.h>
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <sys/file.h>
#include <fcntl.h>
#include <poll.h>
#include <glob.h>
#include <regex.h>
#include <stdint.h>
#include <dirent.h>
#include <linux/rcar-ipmmu-domains.h>
#include <linux/renesas_uioctl.h>
#include <linux/cmemdrv.h>
#include <linux/membarrier.h>
