ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk
-include $(PROJECT_ROOT)/roots.mk

define PINFO
PINFO DESCRIPTION=DISCOM test program
endef

NAME=discom_test
USEFILE = $(PROJECT_ROOT)/Usemsg
INSTALLDIR = usr/bin

include $(MKFILES_ROOT)/qtargets.mk

CCFLAGS+=-Wall
LIBS+=screen img

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../install
   USE_INSTALL_ROOT=1
##############################################################
