/**
 * @file osal_test_common.c
 * @brief OSAL test application common module file.
 * @author K.Takagi
 * @date 2019/11/12
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#include "rcar-xos/osal/r_osal.h"
#include "osal_test.h"
#include "osal_test_common.h"

#if OSAL_S0S1COV
#include "s0s1_macro.h"
#endif	/* OSAL_S0S1COV */


#if OSAL_S0S1COV
S0S1_EXTERN(r_osal_dev_cfg);
S0S1_EXTERN(r_osal_usr_cfg);
S0S1_EXTERN(r_osal_common);
S0S1_EXTERN(r_osal_interrupt);
S0S1_EXTERN(r_osal_io);
S0S1_EXTERN(r_osal_message);
S0S1_EXTERN(r_osal_power);
S0S1_EXTERN(r_osal_thread);
S0S1_EXTERN(r_osal_threadsync);
S0S1_EXTERN(r_osal_timeclock);
S0S1_EXTERN(r_osal_memory);

static uint32_t count_s0, count_s1;


#endif

#if OSAL_S0S1COV
S0S1_EXTERN(r_osal_dev_cfg);
S0S1_EXTERN(r_osal_usr_cfg);
S0S1_EXTERN(r_osal_common);
S0S1_EXTERN(r_osal_interrupt);
S0S1_EXTERN(r_osal_io);
S0S1_EXTERN(r_osal_message);
S0S1_EXTERN(r_osal_power);
S0S1_EXTERN(r_osal_thread);
S0S1_EXTERN(r_osal_threadsync);
S0S1_EXTERN(r_osal_timeclock);
S0S1_EXTERN(r_osal_memory);

static uint32_t count_s0, count_s1;



#endif


/* interim measures : exchange table for old error code to new error code */
/* TODO: Replace implementation */
enum {
	OSAL_ERR_INVALID_TYPE               = OSAL_RETURN_PAR,
	OSAL_ERR_INVALID_ARGUMENT           = OSAL_RETURN_PAR,
	OSAL_ERR_BUFFER_OVER                = OSAL_RETURN_PAR,
	OSAL_ERR_MEMORY_ALLOCATION_FAIL     = OSAL_RETURN_MEM,
	OSAL_ERR_HW_FAULT                   = OSAL_RETURN_DEV,
	OSAL_ERR_TIMEOUT                    = OSAL_RETURN_TIME,
	OSAL_ERR_INVALID_CONFIGURATION      = OSAL_RETURN_CONF,
    OSAL_ERR_OUT_OF_RANGE               = OSAL_RETURN_CONF,
	OSAL_ERR_EFAIL                      = OSAL_RETURN_FAIL,
	OSAL_ERR_IO_ALIGNMENT               = OSAL_RETURN_IO,
	OSAL_ERR_IO_ACCESS                  = OSAL_RETURN_IO,
    OSAL_ERR_OBJECT_ID_ALREADY_ASSIGNED = OSAL_RETURN_BUSY,
    OSAL_ERR_RUNNING_RESOURCE           = OSAL_RETURN_BUSY,
	OSAL_ERR_OBJECT_ID_UNKNOW           = OSAL_RETURN_ID,
	OSAL_ERR_INVALID_HANDLE             = OSAL_RETURN_HANDLE,
	OSAL_ERR_UNEXECUTABLE_STATE         = OSAL_RETURN_STATE,
};

/* define */
#define OSAL_TEST_EXPECT_DATA_TABLE_MAX (888)

/* OSAL test Application expect value table. */
osal_test_expect_data_t expect_data[OSAL_TEST_EXPECT_DATA_TABLE_MAX] = 
{ 
/******************************************************
	OSAL Thread Manager
******************************************************/
/*---------------------------------------------------------------------------------------------------------------*/
/*  OSAL Manager                    API ID                                      TEST ID             Expect Data  */
/*---------------------------------------------------------------------------------------------------------------*/

	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID007,	OSAL_RETURN_ID},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID008,	OSAL_RETURN_ID},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID009,	OSAL_RETURN_BUSY},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID010,	OSAL_RETURN_STATE},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID011,	OSAL_RETURN_STATE},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADCREATE,						OSAL_TEST_ID012,	OSAL_RETURN_FAIL},

	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSLEEPUNTILTIMESTAMP,		OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSLEEPUNTILTIMESTAMP,		OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSLEEPUNTILTIMESTAMP,		OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSLEEPUNTILTIMESTAMP,		OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSLEEPUNTILTIMESTAMP,		OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSLEEPUNTILTIMESTAMP,		OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSLEEPUNTILTIMESTAMP,		OSAL_TEST_ID007,	OSAL_RETURN_OK},

	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSLEEPFORTIMEPERIOD,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSLEEPFORTIMEPERIOD,			OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSLEEPFORTIMEPERIOD,			OSAL_TEST_ID003,	OSAL_RETURN_PAR},

	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSELF,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSELF,						OSAL_TEST_ID002,	OSAL_RETURN_PAR},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSELF,						OSAL_TEST_ID003,	OSAL_RETURN_FAIL},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSELF,						OSAL_TEST_ID004,	OSAL_RETURN_STATE},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSELF,						OSAL_TEST_ID005,	OSAL_RETURN_FAIL},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADSELF,						OSAL_TEST_ID006,	OSAL_RETURN_OK},

	{OSAL_TEST_THREAD,				OSAL_TEST_THREADEQUAL,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADEQUAL,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADEQUAL,						OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADEQUAL,						OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADEQUAL,						OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADEQUAL,						OSAL_TEST_ID006,	OSAL_RETURN_STATE},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADEQUAL,						OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADEQUAL,						OSAL_TEST_ID008,	OSAL_RETURN_OK},

	{OSAL_TEST_THREAD,				OSAL_TEST_THREADJOIN,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADJOIN,						OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADJOIN,						OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADJOIN,						OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADJOIN,						OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADJOIN,						OSAL_TEST_ID006,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADJOIN,						OSAL_TEST_ID007,	OSAL_RETURN_STATE},
	
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADINITIALIZETHREADCONFIGST,	OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_THREAD,				OSAL_TEST_THREADINITIALIZETHREADCONFIGST,	OSAL_TEST_ID002,	OSAL_RETURN_PAR},

/******************************************************
	OSAL Synchronization Manager
******************************************************/
/*---------------------------------------------------------------------------------------------------------------*/
/*  OSAL Manager                    API ID                                      TEST ID             Expect Data  */
/*---------------------------------------------------------------------------------------------------------------*/

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXCREATE,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXCREATE,			OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXCREATE,			OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXCREATE,			OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXCREATE,			OSAL_TEST_ID005,	OSAL_RETURN_ID},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXCREATE,			OSAL_TEST_ID006,	OSAL_RETURN_ID},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXCREATE,			OSAL_TEST_ID007,	OSAL_RETURN_BUSY},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXCREATE,			OSAL_TEST_ID008,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXCREATE,			OSAL_TEST_ID009,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXCREATE,			OSAL_TEST_ID010,	OSAL_RETURN_FAIL},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXDESTROY,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXDESTROY,			OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXDESTROY,			OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXDESTROY,			OSAL_TEST_ID004,	OSAL_RETURN_BUSY},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXDESTROY,			OSAL_TEST_ID005,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXDESTROY,			OSAL_TEST_ID006,	OSAL_RETURN_FAIL},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKFORTIMEPERIOD,		OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKFORTIMEPERIOD,		OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKFORTIMEPERIOD,		OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKFORTIMEPERIOD,		OSAL_TEST_ID004,	OSAL_RETURN_TIME},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKFORTIMEPERIOD,		OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKFORTIMEPERIOD,		OSAL_TEST_ID006,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKFORTIMEPERIOD,		OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKFORTIMEPERIOD,		OSAL_TEST_ID008,	OSAL_RETURN_BUSY},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID007,	OSAL_RETURN_PAR},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID008,	OSAL_RETURN_TIME},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID009,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID010,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCMUTEXLOCKUNTILTIMESTAMP,	OSAL_TEST_ID011,	OSAL_RETURN_BUSY},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXTRYLOCK,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXTRYLOCK,			OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXTRYLOCK,			OSAL_TEST_ID003,	OSAL_RETURN_BUSY},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXTRYLOCK,			OSAL_TEST_ID004,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXTRYLOCK,			OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXTRYLOCK,			OSAL_TEST_ID006,	OSAL_RETURN_BUSY},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXTRYLOCK,			OSAL_TEST_ID007,	OSAL_RETURN_BUSY},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXUNLOCK,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXUNLOCK,			OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXUNLOCK,			OSAL_TEST_ID003,	OSAL_RETURN_FAIL},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXUNLOCK,			OSAL_TEST_ID004,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXUNLOCK,			OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXUNLOCK,			OSAL_TEST_ID006,	OSAL_RETURN_FAIL},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCMUTEXUNLOCK,			OSAL_TEST_ID007,	OSAL_RETURN_FAIL},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDCREATE,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDCREATE,				OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDCREATE,				OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDCREATE,				OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDCREATE,				OSAL_TEST_ID005,	OSAL_RETURN_ID},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDCREATE,				OSAL_TEST_ID006,	OSAL_RETURN_ID},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDCREATE,				OSAL_TEST_ID007,	OSAL_RETURN_BUSY},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDCREATE,				OSAL_TEST_ID008,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDCREATE,				OSAL_TEST_ID009,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDCREATE,				OSAL_TEST_ID010,	OSAL_RETURN_FAIL},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDDESTROY,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDDESTROY,			OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDDESTROY,			OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDDESTROY,			OSAL_TEST_ID004,	OSAL_RETURN_BUSY},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDDESTROY,			OSAL_TEST_ID005,	OSAL_RETURN_BUSY},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDDESTROY,			OSAL_TEST_ID006,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDDESTROY,			OSAL_TEST_ID007,	OSAL_RETURN_FAIL},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITFORTIMEPERIOD,		OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITFORTIMEPERIOD,		OSAL_TEST_ID002,	OSAL_RETURN_TIME},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITFORTIMEPERIOD,		OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITFORTIMEPERIOD,		OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITFORTIMEPERIOD,		OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITFORTIMEPERIOD,		OSAL_TEST_ID006,	OSAL_RETURN_TIME},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITFORTIMEPERIOD,		OSAL_TEST_ID007,	OSAL_RETURN_FAIL},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITFORTIMEPERIOD,		OSAL_TEST_ID008,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITFORTIMEPERIOD,		OSAL_TEST_ID009,	OSAL_RETURN_FAIL},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID006,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID007,	OSAL_RETURN_PAR},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID009,	OSAL_RETURN_TIME},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID010,	OSAL_RETURN_FAIL},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID011,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THSYNCCONDWAITUNTILTIMESTAMP,		OSAL_TEST_ID012,	OSAL_RETURN_FAIL},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDBROADCAST,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDBROADCAST,			OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDBROADCAST,			OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDBROADCAST,			OSAL_TEST_ID004,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDBROADCAST,			OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDBROADCAST,			OSAL_TEST_ID006,	OSAL_RETURN_FAIL},

	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDSIGNAL,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDSIGNAL,				OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDSIGNAL,				OSAL_TEST_ID003,	OSAL_RETURN_STATE},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDSIGNAL,				OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_SYNCHRONIZATION,		OSAL_TEST_THREADSYNCCONDSIGNAL,				OSAL_TEST_ID005,	OSAL_RETURN_FAIL},


/******************************************************
	OSAL Message Manager
******************************************************/
/*---------------------------------------------------------------------------------------------------------------*/
/*  OSAL Manager                    API ID                                      TEST ID             Expect Data  */
/*---------------------------------------------------------------------------------------------------------------*/
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQCREATE,							OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQCREATE,							OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQCREATE,							OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQCREATE,							OSAL_TEST_ID004,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQCREATE,							OSAL_TEST_ID005,	OSAL_ERR_OBJECT_ID_UNKNOW},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQCREATE,							OSAL_TEST_ID006,	OSAL_ERR_OBJECT_ID_UNKNOW},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQCREATE,							OSAL_TEST_ID007,	OSAL_ERR_OBJECT_ID_ALREADY_ASSIGNED},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQCREATE,							OSAL_TEST_ID008,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQCREATE,							OSAL_TEST_ID009,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQCREATE,							OSAL_TEST_ID010,	OSAL_ERR_EFAIL},

	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQDELETE,							OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQDELETE,							OSAL_TEST_ID002,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQDELETE,							OSAL_TEST_ID003,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQDELETE,							OSAL_TEST_ID004,	OSAL_ERR_RUNNING_RESOURCE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQDELETE,							OSAL_TEST_ID005,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQDELETE,							OSAL_TEST_ID006,	OSAL_ERR_RUNNING_RESOURCE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQDELETE,							OSAL_TEST_ID007,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQDELETE,							OSAL_TEST_ID008,	OSAL_ERR_EFAIL},

	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID005,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID006,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID007,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID009,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID010,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID011,	OSAL_ERR_TIMEOUT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID012,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID013,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDUNTILTIMESTAMP,					OSAL_TEST_ID014,	OSAL_ERR_RUNNING_RESOURCE},

	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID003,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID004,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID005,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID007,	OSAL_ERR_BUFFER_OVER},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID008,	OSAL_ERR_TIMEOUT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID009,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID010,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQSENDFORTIMEPERIOD,						OSAL_TEST_ID011,	OSAL_ERR_RUNNING_RESOURCE},

	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID005,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID006,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID007,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID008,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID009,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID010,	OSAL_ERR_TIMEOUT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID011,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID012,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEUNTILTIMESTAMP,				OSAL_TEST_ID013,	OSAL_ERR_RUNNING_RESOURCE},

	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID003,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID004,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID005,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID006,	OSAL_ERR_BUFFER_OVER},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID007,	OSAL_ERR_TIMEOUT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID008,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID009,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID010,	OSAL_ERR_RUNNING_RESOURCE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRECEIVEFORTIMEPERIOD,					OSAL_TEST_ID011,	OSAL_RETURN_OK},

	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISFULL,							OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISFULL,							OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISFULL,							OSAL_TEST_ID003,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISFULL,							OSAL_TEST_ID004,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISFULL,							OSAL_TEST_ID005,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISFULL,							OSAL_TEST_ID006,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISFULL,							OSAL_TEST_ID007,	OSAL_RETURN_OK},

	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISEMPTY,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISEMPTY,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISEMPTY,						OSAL_TEST_ID003,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISEMPTY,						OSAL_TEST_ID004,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISEMPTY,						OSAL_TEST_ID005,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISEMPTY,						OSAL_TEST_ID006,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQISEMPTY,						OSAL_TEST_ID007,	OSAL_RETURN_OK},

	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQGETCONFIG,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQGETCONFIG,						OSAL_TEST_ID002,	OSAL_ERR_INVALID_ARGUMENT},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQGETCONFIG,						OSAL_TEST_ID003,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQGETCONFIG,						OSAL_TEST_ID004,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQGETCONFIG,						OSAL_TEST_ID005,	OSAL_RETURN_OK},

	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRESET,							OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRESET,							OSAL_TEST_ID002,	OSAL_ERR_INVALID_HANDLE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRESET,							OSAL_TEST_ID003,	OSAL_ERR_UNEXECUTABLE_STATE},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQRESET,							OSAL_TEST_ID004,	OSAL_ERR_EFAIL},
	
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQINITIALIZEMQCONFIGST,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MESSAGE,				OSAL_TEST_MQINITIALIZEMQCONFIGST,			OSAL_TEST_ID002,	OSAL_ERR_INVALID_ARGUMENT},

/******************************************************
	OSAL Clock&Time Manager 
******************************************************/
/*---------------------------------------------------------------------------------------------------------------*/
/*  OSAL Manager                    API ID                                      TEST ID             Expect Data  */
/*---------------------------------------------------------------------------------------------------------------*/
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMEGETTIMESTAMP,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMEGETTIMESTAMP,			OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMEGETTIMESTAMP,			OSAL_TEST_ID003,	OSAL_RETURN_PAR},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMEGETTIMESTAMP,			OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMEGETTIMESTAMP,			OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMEGETTIMESTAMP,			OSAL_TEST_ID006,	OSAL_RETURN_OK},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMEGETTIMESTAMP,			OSAL_TEST_ID007,	OSAL_RETURN_OK},

	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMECALCULATETIMEDIFFERENCE,		OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMECALCULATETIMEDIFFERENCE,		OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMECALCULATETIMEDIFFERENCE,		OSAL_TEST_ID003,	OSAL_RETURN_PAR},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMECALCULATETIMEDIFFERENCE,		OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMECALCULATETIMEDIFFERENCE,		OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMECALCULATETIMEDIFFERENCE,		OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMECALCULATETIMEDIFFERENCE,		OSAL_TEST_ID006,	OSAL_RETURN_OK},
	{OSAL_TEST_CLOCK_TIME,			OSAL_TEST_CLOCKTIMECALCULATETIMEDIFFERENCE,		OSAL_TEST_ID007,	OSAL_RETURN_OK},

/******************************************************
	OSAL Interrupt Manager
******************************************************/
/*---------------------------------------------------------------------------------------------------------------*/
/*  OSAL Manager                    API ID                                      TEST ID             Expect Data  */
/*---------------------------------------------------------------------------------------------------------------*/
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTGETNUMOFIRQCHANNELS,		OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTGETNUMOFIRQCHANNELS,		OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTGETNUMOFIRQCHANNELS,		OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTGETNUMOFIRQCHANNELS,		OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTGETNUMOFIRQCHANNELS,		OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTGETNUMOFIRQCHANNELS,		OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTGETNUMOFIRQCHANNELS,		OSAL_TEST_ID007,	OSAL_RETURN_STATE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTGETNUMOFIRQCHANNELS,		OSAL_TEST_ID008,	OSAL_RETURN_OK},

	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID006,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID007,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID009,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID010,	OSAL_RETURN_BUSY},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID011,	OSAL_RETURN_BUSY},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID012,	OSAL_RETURN_STATE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID013,	OSAL_RETURN_DEV},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID014,	OSAL_RETURN_FAIL},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTREGISTERISR,				OSAL_TEST_ID015,	OSAL_RETURN_FAIL},


	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID007,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID009,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID010,	OSAL_RETURN_BUSY},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID011,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID012,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID013,	OSAL_RETURN_STATE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID014,	OSAL_RETURN_DEV},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTUNREGISTERISR,			OSAL_TEST_ID015,	OSAL_RETURN_FAIL},

	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID008,	OSAL_RETURN_FAIL},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID009,	OSAL_RETURN_STATE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID010,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID011,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID012,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID013,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID014,	OSAL_RETURN_DEV},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTENABLEISR,				OSAL_TEST_ID015,	OSAL_RETURN_FAIL},

	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID008,	OSAL_RETURN_FAIL},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID009,	OSAL_RETURN_STATE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID010,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID011,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID012,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID013,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTDISABLEISR,				OSAL_TEST_ID014,	OSAL_RETURN_FAIL},

	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID006,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID007,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID009,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID010,	OSAL_RETURN_PAR},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID011,	OSAL_RETURN_STATE},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTSETISRPRIORITY,			OSAL_TEST_ID012,	OSAL_RETURN_FAIL},

	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTISISRCONTEXT,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTISISRCONTEXT,			OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_INTERRUPT,			OSAL_TEST_INTERRUPTISISRCONTEXT,			OSAL_TEST_ID003,	OSAL_RETURN_PAR},

/******************************************************
	OSAL IO Manager
******************************************************/
/*---------------------------------------------------------------------------------------------------------------*/
/*  OSAL Manager                    API ID                                      TEST ID             Expect Data  */
/*---------------------------------------------------------------------------------------------------------------*/
	{OSAL_TEST_IO,					OSAL_TEST_IOGETNUMOFDEVICES,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETNUMOFDEVICES,				OSAL_TEST_ID002,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETNUMOFDEVICES,				OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETNUMOFDEVICES,				OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETNUMOFDEVICES,				OSAL_TEST_ID028,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETNUMOFDEVICES,				OSAL_TEST_ID029,	OSAL_RETURN_FAIL},

	{OSAL_TEST_IO,					OSAL_TEST_IOGETDEVICELIST,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETDEVICELIST,					OSAL_TEST_ID002,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETDEVICELIST,					OSAL_TEST_ID003,	OSAL_RETURN_UNKNOWN_NAME},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETDEVICELIST,					OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETDEVICELIST,					OSAL_TEST_ID005,	OSAL_RETURN_FAIL},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETDEVICELIST,					OSAL_TEST_ID006,	OSAL_RETURN_FAIL},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETDEVICELIST,					OSAL_TEST_ID007,	OSAL_RETURN_FAIL},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETDEVICELIST,					OSAL_TEST_ID008,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETDEVICELIST,					OSAL_TEST_ID009,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOGETDEVICELIST,					OSAL_TEST_ID033,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IODEVICEOPEN,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICEOPEN,						OSAL_TEST_ID002,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICEOPEN,						OSAL_TEST_ID003,	OSAL_RETURN_ID},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICEOPEN,						OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICEOPEN,						OSAL_TEST_ID005,	OSAL_RETURN_BUSY},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICEOPEN,						OSAL_TEST_ID006,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICEOPEN,						OSAL_TEST_ID007,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICEOPEN,						OSAL_TEST_ID008,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICEOPEN,						OSAL_TEST_ID070,	OSAL_RETURN_FAIL},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICEOPEN,						OSAL_TEST_ID071,	OSAL_RETURN_CONF},

	{OSAL_TEST_IO,					OSAL_TEST_IODEVICECLOSE,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICECLOSE,					OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICECLOSE,					OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICECLOSE,					OSAL_TEST_ID004,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICECLOSE,					OSAL_TEST_ID066,	OSAL_RETURN_FAIL},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICECLOSE,					OSAL_TEST_ID067,	OSAL_RETURN_DEV},
	{OSAL_TEST_IO,					OSAL_TEST_IODEVICECLOSE,					OSAL_TEST_ID068,	OSAL_RETURN_BUSY},

	{OSAL_TEST_IO,					OSAL_TEST_IOREAD8,							OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD8,							OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD8,							OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD8,							OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD8,							OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD8,							OSAL_TEST_ID006,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD8,							OSAL_TEST_ID007,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD8,							OSAL_TEST_ID008,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOREAD16,							OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD16,							OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD16,							OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD16,							OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD16,							OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD16,							OSAL_TEST_ID006,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD16,							OSAL_TEST_ID007,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD16,							OSAL_TEST_ID008,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOREAD32,							OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD32,							OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD32,							OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD32,							OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD32,							OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD32,							OSAL_TEST_ID006,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD32,							OSAL_TEST_ID007,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD32,							OSAL_TEST_ID008,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOREAD64,							OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD64,							OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD64,							OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD64,							OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD64,							OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD64,							OSAL_TEST_ID006,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD64,							OSAL_TEST_ID007,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOREAD64,							OSAL_TEST_ID008,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE8,							OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE8,							OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE8,							OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE8,							OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE8,							OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE8,							OSAL_TEST_ID006,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE8,							OSAL_TEST_ID007,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE16,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE16,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE16,						OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE16,						OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE16,						OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE16,						OSAL_TEST_ID006,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE16,						OSAL_TEST_ID007,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE32,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE32,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE32,						OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE32,						OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE32,						OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE32,						OSAL_TEST_ID006,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE32,						OSAL_TEST_ID007,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE64,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE64,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE64,						OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE64,						OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE64,						OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE64,						OSAL_TEST_ID006,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOWRITE64,						OSAL_TEST_ID007,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID009,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID010,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD8,						OSAL_TEST_ID011,	OSAL_RETURN_OK},


	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID009,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID010,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD16,					OSAL_TEST_ID011,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID009,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID010,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD32,					OSAL_TEST_ID011,	OSAL_RETURN_OK},


	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID009,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID010,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKREAD64,					OSAL_TEST_ID011,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID009,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID010,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE8,					OSAL_TEST_ID011,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID009,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID010,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE16,					OSAL_TEST_ID011,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID009,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID010,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE32,					OSAL_TEST_ID011,	OSAL_RETURN_OK},

	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID005,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID009,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID010,	OSAL_RETURN_STATE},
	{OSAL_TEST_IO,					OSAL_TEST_IOBLOCKWRITE64,					OSAL_TEST_ID011,	OSAL_RETURN_OK},

/******************************************************
	OSAL PM Manager
******************************************************/
/*---------------------------------------------------------------------------------------------------------------*/
/*  OSAL Manager                    API ID                                      TEST ID             Expect Data  */
/*---------------------------------------------------------------------------------------------------------------*/
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
/* This test: Device handle without power control returns OSAL_RETURN_FAIL.
   However, PoC implemetation is not check power control, so returns OSAL_RETURN_OK
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID006,	OSAL_RETURN_FAIL},*/
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID006,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID007,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID009,	OSAL_RETURN_STATE},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID010,	OSAL_RETURN_FAIL},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID011,	OSAL_RETURN_DEV},

	{OSAL_TEST_PM,					OSAL_TEST_PMGETREQUIREDSTATE,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETREQUIREDSTATE,				OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETREQUIREDSTATE,				OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETREQUIREDSTATE,				OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETREQUIREDSTATE,				OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
/* This test: Device handle without power control returns OSAL_RETURN_FAIL.
   However, PoC implemetation is not check power control, so returns OSAL_RETURN_OK
	{OSAL_TEST_PM,					OSAL_TEST_PMSETREQUIREDSTATE,				OSAL_TEST_ID006,	OSAL_RETURN_FAIL}, */
	{OSAL_TEST_PM,					OSAL_TEST_PMGETREQUIREDSTATE,				OSAL_TEST_ID006,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETREQUIREDSTATE,				OSAL_TEST_ID007,	OSAL_RETURN_STATE},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETREQUIREDSTATE,				OSAL_TEST_ID008,	OSAL_RETURN_FAIL},

	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID006,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID008,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID009,	OSAL_RETURN_TIME},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID010,	OSAL_RETURN_TIME},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID011,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID012,	OSAL_RETURN_HANDLE},
/* This test: Device handle without power control returns OSAL_RETURN_FAIL.
   However, PoC implemetation is not check power control, so returns OSAL_RETURN_OK
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID013,	OSAL_RETURN_FAIL}, */
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID013,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID014,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID015,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID016,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID017,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID018,	OSAL_RETURN_STATE},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETANDWAITFORSTATE,				OSAL_TEST_ID019,	OSAL_RETURN_FAIL},

	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID006,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID007,	OSAL_RETURN_HANDLE},
/* This test: Device handle without power control returns OSAL_RETURN_FAIL.
   However, PoC implemetation is not check power control, so returns OSAL_RETURN_OK
   	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID008,	OSAL_RETURN_FAIL}, */
   	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID008,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID009,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID010,	OSAL_RETURN_STATE},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETSTATE,						OSAL_TEST_ID011,	OSAL_RETURN_FAIL},

	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID006,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID007,	OSAL_RETURN_HANDLE},
/* This test: Device handle without power control returns OSAL_RETURN_FAIL.
   However, PoC implemetation is not check power control, so returns OSAL_RETURN_OK
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID008,	OSAL_RETURN_FAIL}, */
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID008,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID009,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID010,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID011,	OSAL_RETURN_STATE},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETPOLICY,						OSAL_TEST_ID012,	OSAL_RETURN_FAIL},

	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID004,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID006,	OSAL_RETURN_HANDLE},
/* This test: Device handle without power control returns OSAL_RETURN_FAIL.
   However, PoC implemetation is not check power control, so returns OSAL_RETURN_OK
	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID007,	OSAL_RETURN_FAIL}, */
	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID007,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID008,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID009,	OSAL_RETURN_STATE},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETPOLICY,						OSAL_TEST_ID010,	OSAL_RETURN_FAIL},

	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
/* This test: Device handle without power control returns OSAL_RETURN_FAIL.
   However, PoC implemetation is not check power control, so returns OSAL_RETURN_OK
	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID005,	OSAL_RETURN_FAIL}, */
	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID005,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID007,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID008,	OSAL_RETURN_STATE},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID009,	OSAL_RETURN_FAIL},
	{OSAL_TEST_PM,					OSAL_TEST_PMSETRESETSTATE,					OSAL_TEST_ID010,	OSAL_RETURN_DEV},

	{OSAL_TEST_PM,					OSAL_TEST_PMGETRESETSTATE,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETRESETSTATE,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETRESETSTATE,					OSAL_TEST_ID003,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETRESETSTATE,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETRESETSTATE,					OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
/* This test: Device handle without power control returns OSAL_RETURN_FAIL.
   However, PoC implemetation is not check power control, so returns OSAL_RETURN_OK
	{OSAL_TEST_PM,					OSAL_TEST_PMGETRESETSTATE,					OSAL_TEST_ID006,	OSAL_RETURN_FAIL}, */
	{OSAL_TEST_PM,					OSAL_TEST_PMGETRESETSTATE,					OSAL_TEST_ID006,	OSAL_RETURN_OK},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETRESETSTATE,					OSAL_TEST_ID007,	OSAL_RETURN_PAR},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETRESETSTATE,					OSAL_TEST_ID008,	OSAL_RETURN_STATE},
	{OSAL_TEST_PM,					OSAL_TEST_PMGETRESETSTATE,					OSAL_TEST_ID009,	OSAL_RETURN_FAIL},

/******************************************************
	OSAL Common Function
******************************************************/
/*---------------------------------------------------------------------------------------------------------------*/
/*  OSAL Manager                    API ID                                      TEST ID             Expect Data  */
/*---------------------------------------------------------------------------------------------------------------*/
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID002,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID003,	OSAL_RETURN_CONF},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID004,	OSAL_RETURN_CONF},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID005,	OSAL_RETURN_CONF},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID006,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID007,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID008,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID009,	OSAL_RETURN_CONF},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID010,	OSAL_RETURN_CONF},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID011,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID012,	OSAL_RETURN_CONF},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID013,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID014,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID015,	OSAL_RETURN_CONF},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID016,	OSAL_RETURN_CONF},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID017,	OSAL_RETURN_CONF},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID018,	OSAL_RETURN_STATE},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID019,	OSAL_RETURN_OK},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID020,	OSAL_RETURN_MEM},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID021,	OSAL_RETURN_DEV},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_INIT,						OSAL_TEST_ID022,	OSAL_RETURN_OK},

	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_DEINIT,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_DEINIT,					OSAL_TEST_ID002,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_DEINIT,					OSAL_TEST_ID003,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_DEINIT,					OSAL_TEST_ID004,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_DEINIT,					OSAL_TEST_ID005,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_DEINIT,					OSAL_TEST_ID006,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_DEINIT,					OSAL_TEST_ID007,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_DEINIT,					OSAL_TEST_ID008,	OSAL_RETURN_FAIL},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_DEINIT,					OSAL_TEST_ID009,	OSAL_RETURN_DEV},
	{OSAL_TEST_COMMON_FUNCTION,		OSAL_TEST_COMMON_DEINIT,					OSAL_TEST_ID010,	OSAL_RETURN_FAIL},

/******************************************************
	OSAL Memory Manager
******************************************************/
/*---------------------------------------------------------------------------------------------------------------*/
/*  OSAL Manager                    API ID                                      TEST ID             Expect Data  */
/*---------------------------------------------------------------------------------------------------------------*/
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID002,	OSAL_RETURN_STATE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID003,	OSAL_RETURN_PAR},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID005,	OSAL_RETURN_CONF},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID006,	OSAL_RETURN_CONF},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID007,	OSAL_RETURN_CONF},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID008,	OSAL_RETURN_CONF},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID009,	OSAL_RETURN_CONF},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID010,	OSAL_RETURN_CONF},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGROPEN,						OSAL_TEST_ID011,	OSAL_RETURN_CONF},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRCLOSE,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRCLOSE,						OSAL_TEST_ID002,	OSAL_RETURN_STATE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRCLOSE,						OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRCLOSE,						OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRALLOC,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRALLOC,						OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRALLOC,						OSAL_TEST_ID003,	OSAL_RETURN_PAR},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRALLOC,						OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRALLOC,						OSAL_TEST_ID005,	OSAL_RETURN_HANDLE_NOT_SUPPORTED},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRALLOC,						OSAL_TEST_ID006,	OSAL_RETURN_CONF},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRALLOC,						OSAL_TEST_ID007,	OSAL_RETURN_OK},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEALLOC,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEALLOC,						OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEALLOC,						OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEALLOC,						OSAL_TEST_ID004,	OSAL_RETURN_HANDLE_NOT_SUPPORTED},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEALLOC,						OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCONFIG,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCONFIG,					OSAL_TEST_ID002,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCONFIG,					OSAL_TEST_ID003,	OSAL_RETURN_PAR},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCONFIG,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE_NOT_SUPPORTED},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETOSALMAXCONFIG,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETOSALMAXCONFIG,			OSAL_TEST_ID002,	OSAL_RETURN_PAR},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRINITIALIZEMMNGRCONFIGST,		OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRINITIALIZEMMNGRCONFIGST,		OSAL_TEST_ID002,	OSAL_RETURN_PAR},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRREGISTERMONITOR,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRREGISTERMONITOR,				OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRREGISTERMONITOR,				OSAL_TEST_ID003,	OSAL_RETURN_PAR},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRREGISTERMONITOR,				OSAL_TEST_ID004,	OSAL_RETURN_PAR},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRREGISTERMONITOR,				OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRREGISTERMONITOR,				OSAL_TEST_ID006,	OSAL_RETURN_PAR},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRREGISTERMONITOR,				OSAL_TEST_ID007,	OSAL_RETURN_PAR},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRREGISTERMONITOR,				OSAL_TEST_ID008,	OSAL_RETURN_HANDLE_NOT_SUPPORTED},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCPUPTR,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCPUPTR,					OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCPUPTR,					OSAL_TEST_ID003,	OSAL_RETURN_PAR},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCPUPTR,					OSAL_TEST_ID004,	OSAL_RETURN_UNSUPPORTED_OPERATION},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCPUPTR,					OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCONSTCPUPTR,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCONSTCPUPTR,				OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCONSTCPUPTR,				OSAL_TEST_ID003,	OSAL_RETURN_PAR},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCONSTCPUPTR,				OSAL_TEST_ID004,	OSAL_RETURN_UNSUPPORTED_OPERATION},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETCONSTCPUPTR,				OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRFLUSH,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRFLUSH,						OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRFLUSH,						OSAL_TEST_ID003,	OSAL_RETURN_UNSUPPORTED_OPERATION},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRFLUSH,						OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRINVALIDATE,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRINVALIDATE,					OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRINVALIDATE,					OSAL_TEST_ID003,	OSAL_RETURN_UNSUPPORTED_OPERATION},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRINVALIDATE,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETHWADDR,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETHWADDR,					OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETHWADDR,					OSAL_TEST_ID003,	OSAL_RETURN_UNSUPPORTED_OPERATION},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETHWADDR,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETHWADDR,					OSAL_TEST_ID005,	OSAL_RETURN_PAR},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETSIZE,						OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETSIZE,						OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETSIZE,						OSAL_TEST_ID003,	OSAL_RETURN_UNSUPPORTED_OPERATION},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETSIZE,						OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRGETSIZE,						OSAL_TEST_ID005,	OSAL_RETURN_PAR},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRCHECKBUFFER,					OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRCHECKBUFFER,					OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRCHECKBUFFER,					OSAL_TEST_ID003,	OSAL_RETURN_UNSUPPORTED_OPERATION},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRCHECKBUFFER,					OSAL_TEST_ID004,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRCHECKBUFFER,					OSAL_TEST_ID005,	OSAL_RETURN_MEM},

#if IT_DEBUG_ON
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEBUGMMNGRPRINT,				OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEBUGMMNGRPRINT,				OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEBUGMMNGRPRINT,				OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEBUGMMNGRPRINT,				OSAL_TEST_ID004,	OSAL_RETURN_UNSUPPORTED_OPERATION},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEBUGMMNGRPRINT,				OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},

	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEBUGBUFFERPRINT,			OSAL_TEST_ID001,	OSAL_RETURN_OK},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEBUGBUFFERPRINT,			OSAL_TEST_ID002,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEBUGBUFFERPRINT,			OSAL_TEST_ID003,	OSAL_RETURN_HANDLE},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEBUGBUFFERPRINT,			OSAL_TEST_ID004,	OSAL_RETURN_UNSUPPORTED_OPERATION},
	{OSAL_TEST_MEMORY,		OSAL_TEST_MMNGRDEBUGBUFFERPRINT,			OSAL_TEST_ID005,	OSAL_RETURN_HANDLE},
#endif
};


void osal_test_result_output(int parent, int api_id, int test_id, int result, char *param) 
{

	if (param == NULL)
	{

		if (result == OSAL_TEST_OK)
		{
			printf("test case %02d_%03d_%03d result OK.\n\n", parent, api_id, test_id);
		}
		else
		{
			printf("test case %02d_%03d_%03d result NG.\n\n", parent, api_id, test_id);
		}
	}
	else
	{

		if (result == OSAL_TEST_OK)
		{
			printf("test case %02d_%03d_%03d result OK. %s\n\n", parent, api_id, test_id, param);
			test_pass ++;
		} 
		else 
		{
			printf("test case %02d_%03d_%03d result NG. %s\n\n", parent, api_id, test_id, param);
			test_fail ++;
		}
	}
}

uint64_t osal_test_get_expectdata(OSAL_TEST_PARENT_ID parent, OSAL_TEST_API_ID api_id, OSAL_TEST_ID test_id) 
{

	unsigned int  count    = 0;
	e_osal_return_t osal_ret = OSAL_RETURN_OK;

	/* expect data search */
	for(count = 0; count < OSAL_TEST_EXPECT_DATA_TABLE_MAX; count++)
	{

		if ((expect_data[count].parent_id == parent) &&
			(expect_data[count].api_id    == api_id) &&
			(expect_data[count].test_id   == test_id))
		{
			osal_ret = expect_data[count].expect;
			break;
		}
	}

	if (count == OSAL_TEST_EXPECT_DATA_TABLE_MAX)
	{
		printf("expect data is not registered. %02d_%03d_%03d \n", parent, api_id, test_id);
	}

	return (uint64_t)osal_ret;

}

#ifdef TARGET_LINUX

void osal_test_initialize_serialport()
{
	/* No processing is required on Linux. */
}


void osal_test_get_testid(char *test_number, unsigned int input_count)
{

	/* this linux route is not evaluated. */
	if (fgets(test_number, OSAL_TEST_ID_MAX, stdin) == NULL || test_number[0] == '\n')
	{
		printf("input value error.\n");
		return;
	}

	return;
}

#endif

e_osal_return_t osal_init(void)
{
    e_osal_return_t ret = OSAL_RETURN_OK;
	ret = R_OSAL_Initialize();

    return ret;
}


e_osal_return_t osal_deinit(void)
{
    e_osal_return_t ret = OSAL_RETURN_OK;
	ret = R_OSAL_Deinitialize();
    return ret;
}

char *osal_ret_to_str(e_osal_return_t ret_val)
{
    static char *str;
    
    switch(ret_val)
    {
        case OSAL_RETURN_OK:
            str = "OSAL_RETURN_OK";
            break;
        case OSAL_RETURN_PAR:
            str = "OSAL_RETURN_PAR";
            break;

        case OSAL_RETURN_MEM:
            str = "OSAL_RETURN_MEM";
            break;

        case OSAL_RETURN_DEV:
            str = "OSAL_RETURN_DEV";
            break;

        case OSAL_RETURN_TIME:
            str = "OSAL_RETURN_TIME";
            break;

        case OSAL_RETURN_CONF:
            str = "OSAL_RETURN_CONF";
            break;

        case OSAL_RETURN_FAIL:
            str = "OSAL_RETURN_FAIL";
            break;

        case OSAL_RETURN_IO:
            str = "OSAL_RETURN_IO";
            break;

        case OSAL_RETURN_BUSY:
            str = "OSAL_RETURN_BUSY";
            break;

        case OSAL_RETURN_ID:
            str = "OSAL_RETURN_ID";
            break;

        case OSAL_RETURN_HANDLE:
            str = "OSAL_RETURN_HANDLE";
            break;

        case OSAL_RETURN_STATE:
            str = "OSAL_RETURN_STATE";
            break;

        case OSAL_RETURN_PROHIBITED:
            str = "OSAL_RETURN_PROHIBITED";
            break;

        case OSAL_RETURN_UNSUPPORTED_OPERATION:
            str = "OSAL_RETURN_UNSUPPORTED_OPERATION";
            break;

        case OSAL_RETURN_HANDLE_NOT_SUPPORTED:
            str = "OSAL_RETURN_HANDLE_NOT_SUPPORTED";
            break;

        case OSAL_RETURN_UNKNOWN_NAME:
            str = "OSAL_RETURN_UNKNOWN_NAME";
            break;

        case OSAL_RETURN_CONF_UNSUPPORTED:
            str = "OSAL_RETURN_CONF_UNSUPPORTED";
            break;

        case OSAL_RETURN_OK_RQST:
            str = "OSAL_RETURN_OK_RQST";
            break;

        default:
            str = "UNKNOW ERROR";
            break;

    }

    return str;
}

char * osal_policy_ret_to_str(e_osal_pm_policy_t ret_val)
{	
	static char *str;

    switch(ret_val)
    {
        case OSAL_PM_POLICY_PG:
            str = "OSAL_PM_POLICY_PG \n";
            break;
        case OSAL_PM_POLICY_CG:
            str = "OSAL_PM_POLICY_CG \n";
            break;

        case OSAL_PM_POLICY_HP:
            str = "OSAL_PM_POLICY_HP \n";
            break;
		default:
			str = "OSAL_PM_POLICY_INVALID \n";
			break;
	}

	return str;
}

char *osal_reset_state_ret_to_str(e_osal_pm_reset_state_t ret_val)
{
	static char *str;

    switch(ret_val)
    {
        case OSAL_PM_RESET_STATE_APPLIED:
            str = "OSAL_PM_RESET_STATE_APPLIED \n";
            break;
        case OSAL_PM_RESET_STATE_RELEASED:
            str = "OSAL_PM_RESET_STATE_RELEASED \n";
            break;
		default:
			str = "OSAL_PM_RESET_STATE_INVALID \n";
			break;
	}
	
	return str;
}

#if OSAL_S0S1COV
/***********************************************************
 * Function: reset_s0s1_info
 *
 * Reset information for S0/S1 coverage.
 */
void reset_s0s1_info(void)
{
	unsigned char	*b;
	unsigned int	size;

	S0S1_GETINFO(r_osal_dev_cfg, b, size);		memset(b, 0, size);
	S0S1_GETINFO(r_osal_usr_cfg, b, size);		memset(b, 0, size);
	S0S1_GETINFO(r_osal_common, b, size);		memset(b, 0, size);
	S0S1_GETINFO(r_osal_interrupt, b, size);	memset(b, 0, size);
	S0S1_GETINFO(r_osal_io, b, size);			memset(b, 0, size);
	S0S1_GETINFO(r_osal_message, b, size);		memset(b, 0, size);
	S0S1_GETINFO(r_osal_power, b, size);		memset(b, 0, size);
	S0S1_GETINFO(r_osal_thread, b, size);		memset(b, 0, size);
	S0S1_GETINFO(r_osal_threadsync, b, size);	memset(b, 0, size);
	S0S1_GETINFO(r_osal_timeclock, b, size);	memset(b, 0, size);
	S0S1_GETINFO(r_osal_memory, b, size);		memset(b, 0, size);
}

/***********************************************************
 * Function: print_s0s1log
 *
 * Output S0/S1 Log with printf.
 */
static void print_s0s1log(const char *file, unsigned char *b, unsigned int length)
{
	size_t			i;
	const int		S0_FLAG	= 0x1;
	const int		S1_FLAG	= 0x2;
	printf("----------------------------\nS0/S1 mark info for %s\n", file);
	for (i = 0; i < length; i++)
	{
		if (b[i] & S0_FLAG)
		{
		    count_s0++;
		}
		if (b[i] & S1_FLAG)
		{
		    count_s1++;
		}
		printf("%u\n", (uint32_t)b[i]);
	}
}

/***********************************************************
 * Function: showt_s0s1_info
 *
 * Output S0/S1 Log with printf.
 */
void showt_s0s1_info(void)
{
	unsigned char	*b;
	unsigned int	size;

	count_s0 = count_s1 = 0;

	S0S1_GETINFO(r_osal_dev_cfg, b, size);		print_s0s1log("r_osal_dev_cfg",		b, size);
	S0S1_GETINFO(r_osal_usr_cfg, b, size);		print_s0s1log("r_osal_usr_cfg",		b, size);
	S0S1_GETINFO(r_osal_common, b, size);		print_s0s1log("r_osal_common",		b, size);
	S0S1_GETINFO(r_osal_interrupt, b, size);	print_s0s1log("r_osal_interrupt",	b, size);
	S0S1_GETINFO(r_osal_io, b, size);			print_s0s1log("r_osal_io",			b, size);
	S0S1_GETINFO(r_osal_message, b, size);		print_s0s1log("r_osal_message",		b, size);
	S0S1_GETINFO(r_osal_power, b, size);		print_s0s1log("r_osal_power",		b, size);
	S0S1_GETINFO(r_osal_thread, b, size);		print_s0s1log("r_osal_thread",		b, size);
	S0S1_GETINFO(r_osal_threadsync, b, size);	print_s0s1log("r_osal_threadsync",	b, size);
	S0S1_GETINFO(r_osal_timeclock, b, size);	print_s0s1log("r_osal_timeclock",	b, size);
	S0S1_GETINFO(r_osal_memory, b, size);		print_s0s1log("r_osal_memory",		b, size);

	printf("----------------------------\ntotal S0 mark: %u\ntotal S1 mark: %u\n", count_s0, count_s1);
}
#endif	/* S0S1COV */
