#include "testenv.h"

TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0001) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 1)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0002) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 2)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0003) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 3)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0004) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 4)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0005) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 5)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0006) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 6)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0007) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 7)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0008) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 8)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0009) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 9)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0010) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 10)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0011) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 11)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0012) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 12)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0013) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 13)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0014) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 14)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0015) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 15)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0016) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 16)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0017) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 17)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0018) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 18)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0019) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 19)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0020) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 20)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0021) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 21)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0022) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 22)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0023) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 23)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0024) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 24)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0025) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 25)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0026) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 26)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0027) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 27)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0028) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 28)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0029) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 29)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0030) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 30)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0031) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 31)); }
TEST_CASE_F(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0032) { EXPECT_EQ( true, TEST_R_IMPDRV_SetIrqGroup("PCL", 32)); }

struct TestCase UT_R_IMPDRV_SetIrqGroup_All_Tests[] = {
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0001, R_IMPDRV_SetIrqGroup_0001),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0002, R_IMPDRV_SetIrqGroup_0002),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0003, R_IMPDRV_SetIrqGroup_0003),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0004, R_IMPDRV_SetIrqGroup_0004),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0005, R_IMPDRV_SetIrqGroup_0005),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0006, R_IMPDRV_SetIrqGroup_0006),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0007, R_IMPDRV_SetIrqGroup_0007),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0008, R_IMPDRV_SetIrqGroup_0008),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0009, R_IMPDRV_SetIrqGroup_0009),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0010, R_IMPDRV_SetIrqGroup_0010),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0011, R_IMPDRV_SetIrqGroup_0011),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0012, R_IMPDRV_SetIrqGroup_0012),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0013, R_IMPDRV_SetIrqGroup_0013),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0014, R_IMPDRV_SetIrqGroup_0014),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0015, R_IMPDRV_SetIrqGroup_0015),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0016, R_IMPDRV_SetIrqGroup_0016),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0017, R_IMPDRV_SetIrqGroup_0017),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0018, R_IMPDRV_SetIrqGroup_0018),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0019, R_IMPDRV_SetIrqGroup_0019),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0020, R_IMPDRV_SetIrqGroup_0020),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0021, R_IMPDRV_SetIrqGroup_0021),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0022, R_IMPDRV_SetIrqGroup_0022),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0023, R_IMPDRV_SetIrqGroup_0023),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0024, R_IMPDRV_SetIrqGroup_0024),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0025, R_IMPDRV_SetIrqGroup_0025),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0026, R_IMPDRV_SetIrqGroup_0026),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0027, R_IMPDRV_SetIrqGroup_0027),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0028, R_IMPDRV_SetIrqGroup_0028),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0029, R_IMPDRV_SetIrqGroup_0029),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0030, R_IMPDRV_SetIrqGroup_0030),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0031, R_IMPDRV_SetIrqGroup_0031),
	TEST_CASE_T(UT, R_IMPDRV_SetIrqGroup, V4M, R_IMPDRV_SetIrqGroup_0032, R_IMPDRV_SetIrqGroup_0032),
	TEST_CASE_END
};
