#include "testenv.h"

TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0001) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 1)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0002) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 2)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0003) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 3)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0004) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 4)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0005) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 5)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0006) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 6)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0007) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 7)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0008) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 8)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0009) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 9)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0010) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 10)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0011) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 11)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0012) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 12)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0013) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 13)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0014) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 14)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0015) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 15)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0016) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 16)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0017) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 17)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0018) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 18)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0019) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 19)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0020) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 20)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0021) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 21)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0022) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 22)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0023) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 23)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0024) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 24)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0025) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 25)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0026) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 26)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0027) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 27)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0028) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 28)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0029) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 29)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0030) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 30)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0031) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 31)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0032) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 32)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0033) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 33)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0034) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 34)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0035) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 35)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0036) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 36)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0037) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 37)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0038) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 38)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0039) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 39)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0040) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 40)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0041) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 41)); }
TEST_CASE_F(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0042) { EXPECT_EQ( true, TEST_R_IMPDRV_SetPMPolicy("PCL", 42)); }

struct TestCase UT_R_IMPDRV_SetPMPolicy_All_Tests[] = {
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0001, R_IMPDRV_SetPMPolicy_0001),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0002, R_IMPDRV_SetPMPolicy_0002),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0003, R_IMPDRV_SetPMPolicy_0003),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0004, R_IMPDRV_SetPMPolicy_0004),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0005, R_IMPDRV_SetPMPolicy_0005),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0006, R_IMPDRV_SetPMPolicy_0006),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0007, R_IMPDRV_SetPMPolicy_0007),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0008, R_IMPDRV_SetPMPolicy_0008),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0009, R_IMPDRV_SetPMPolicy_0009),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0010, R_IMPDRV_SetPMPolicy_0010),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0011, R_IMPDRV_SetPMPolicy_0011),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0012, R_IMPDRV_SetPMPolicy_0012),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0013, R_IMPDRV_SetPMPolicy_0013),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0014, R_IMPDRV_SetPMPolicy_0014),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0015, R_IMPDRV_SetPMPolicy_0015),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0016, R_IMPDRV_SetPMPolicy_0016),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0017, R_IMPDRV_SetPMPolicy_0017),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0018, R_IMPDRV_SetPMPolicy_0018),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0019, R_IMPDRV_SetPMPolicy_0019),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0020, R_IMPDRV_SetPMPolicy_0020),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0021, R_IMPDRV_SetPMPolicy_0021),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0022, R_IMPDRV_SetPMPolicy_0022),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0023, R_IMPDRV_SetPMPolicy_0023),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0024, R_IMPDRV_SetPMPolicy_0024),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0025, R_IMPDRV_SetPMPolicy_0025),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0026, R_IMPDRV_SetPMPolicy_0026),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0027, R_IMPDRV_SetPMPolicy_0027),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0028, R_IMPDRV_SetPMPolicy_0028),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0029, R_IMPDRV_SetPMPolicy_0029),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0030, R_IMPDRV_SetPMPolicy_0030),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0031, R_IMPDRV_SetPMPolicy_0031),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0032, R_IMPDRV_SetPMPolicy_0032),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0033, R_IMPDRV_SetPMPolicy_0033),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0034, R_IMPDRV_SetPMPolicy_0034),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0035, R_IMPDRV_SetPMPolicy_0035),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0036, R_IMPDRV_SetPMPolicy_0036),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0037, R_IMPDRV_SetPMPolicy_0037),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0038, R_IMPDRV_SetPMPolicy_0038),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0039, R_IMPDRV_SetPMPolicy_0039),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0040, R_IMPDRV_SetPMPolicy_0040),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0041, R_IMPDRV_SetPMPolicy_0041),
	TEST_CASE_T(UT, R_IMPDRV_SetPMPolicy, V4H2, R_IMPDRV_SetPMPolicy_0042, R_IMPDRV_SetPMPolicy_0042),
	TEST_CASE_END
};
