ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

DEVS_PATH=	$(QNX_TARGET)/usr/include/devs
IOS_PATH=	$(QNX_TARGET)/usr/include/io-sock

EXTRA_INCVPATH+= \
	$(DEVS_PATH) \
	$(DEVS_PATH)/contrib/ck/include \
	$(DEVS_PATH)/include_$(CPU) \
	$(DEVS_PATH)/qnx \
	$(DEVS_PATH)/qnx-gen \
	$(DEVS_PATH)/sys-nto \
	$(IOS_PATH)

 #CCFLAGS+= 	-DINVARIANTS -DINVARIANT_SUPPORT -DKTR
 CCFLAGS+=	-Wp,-includegcc-defs.h
 CCFLAGS+=	-fno-builtin-log -fno-strict-aliasing
 CCFLAGS+=	-Wno-pointer-sign -Wno-unused-but-set-variable
 CCFLAGS += -D_KERNEL -DALTQ 
 CCFLAGS += -D__EXT_QNX
# currently doesnt handle individual builtins
CCFLAGS += $(CCFLAGS_$(COMPILER_TYPE))
# CCFLAGS+=	-Werror

LIBS = drvrS netdrvrS drvr

NAME = devs-$(PROJECT)
#NAME = devs-rswitch-diag

USEFILE=$(PROJECT_ROOT)/$(NAME).use

define PINFO
PINFO DESCRIPTION=Renesas R-Car RSwitch Network driver
endef

#CCFLAGS +=	-Wunused-function -Wno-unused-function -Wunused-variable -Wno-unused-variable

# ifneq ($(QNX_ALLOW_WERROR), 0)
# CCFLAGS += -Werror
# endif
#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk


