# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget emcos)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
set(_IMPORT_PREFIX "${_IMPORT_PREFIX}/build")

if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target emcos
string(TOLOWER ${CMAKE_BUILD_TYPE} l_build_type)
if(NOT l_build_type STREQUAL "${l_build_type}")
  set(l_build_type "release")
endif()
add_library(emcos INTERFACE IMPORTED GLOBAL)
set_target_properties(emcos PROPERTIES
INTERFACE_INCLUDE_DIRECTORIES
"${_IMPORT_PREFIX}/parts/include;\
${_IMPORT_PREFIX}/parts/include/pt_api;\
${_IMPORT_PREFIX}/parts/include/tk_api;\
${_IMPORT_PREFIX}/parts/include/generated;\
${_IMPORT_PREFIX}/parts/include_posix;\
${_IMPORT_PREFIX}/parts/lib/libhelper/newlib/libc/include;\
${_IMPORT_PREFIX}/parts/lib/libhelper/newlib/libc/sys/mcos/include;\
${_IMPORT_PREFIX}/parts/config;\
${_IMPORT_PREFIX}/${l_build_type}/config"

INTERFACE_LINK_LIBRARIES
"${_IMPORT_PREFIX}/${l_build_type}/lib/crt0.o;\
${_IMPORT_PREFIX}/${l_build_type}/lib/crtsvc.o;\
${_IMPORT_PREFIX}/${l_build_type}/lib/crtarmclang.o;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libcarmclang.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libposix.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libmcos.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/liblfs.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libpthread.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libprocess.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libmmap.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libtime.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libsem.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libsignal.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libpipe.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libsocket.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libmq.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libnetdb.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libtimer.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libaio.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libalarm.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/liburing.a;\
${_IMPORT_PREFIX}/${l_build_type}/lib/libhelper.a"
)

if(CMAKE_VERSION VERSION_LESS 3.1.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.1.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/rcar-xos-aarch64-armclang-emcos-v4h-export-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
