#include "rcar-xos/imp/r_impdrv.h"
#include "r_impdrv_private.h"
p_impdrv_dspctl_dsp_start_t impdrv_cmnctl_get_dsp_func_stub(void);
extern const st_impdrv_corectl_func_t *impdrv_cmnctl_get_corectl_func_stub(const e_impdrv_core_type_t core_type);

#define impdrv_cmnctl_get_corectl_func impdrv_cmnctl_get_corectl_func_(__LINE__)
#define impdrv_cmnctl_get_corectl_func_(line) impdrv_cmnctl_get_corectl_func__(line)
#define impdrv_cmnctl_get_corectl_func__(line) impdrv_cmnctl_get_corectl_func_ut_##line
#define impdrv_cmnctl_get_corectl_func_ut_472 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_658 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_712 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_775 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_822 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_876 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_931 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_986 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_1032 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_1091 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_1140 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_1189 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_1239 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_1326 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_1398 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_1446 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_1923 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_2005 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_2090 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_2185 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_2289 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_2385 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_2467 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_2642 impdrv_cmnctl_get_corectl_func_stub
#define impdrv_cmnctl_get_corectl_func_ut_2947 impdrv_cmnctl_get_corectl_func_stub

#define impdrv_genctl_init_set_state impdrv_genctl_init_set_state_(__LINE__)
#define impdrv_genctl_init_set_state_(line) impdrv_genctl_init_set_state__(line)
#define impdrv_genctl_init_set_state__(line) impdrv_genctl_init_set_state_ut_##line
#define impdrv_genctl_init_set_state_ut_411 impdrv_genctl_init_set_state_stub
#define impdrv_genctl_init_set_state_ut_234 impdrv_genctl_init_set_state
#define impdrv_genctl_init_set_state_ut_2736 impdrv_genctl_init_set_state

#define impdrv_cmnctl_reg_set_mem_protect impdrv_cmnctl_reg_set_mem_protect_(__LINE__)
#define impdrv_cmnctl_reg_set_mem_protect_(line) impdrv_cmnctl_reg_set_mem_protect__(line)
#define impdrv_cmnctl_reg_set_mem_protect__(line) impdrv_cmnctl_reg_set_mem_protect_ut_##line
#define impdrv_cmnctl_reg_set_mem_protect_ut_1531 impdrv_cmnctl_reg_set_mem_protect_stub


#define impdrv_cmnctl_judge_int impdrv_cmnctl_judge_int_(__LINE__)
#define impdrv_cmnctl_judge_int_(line) impdrv_cmnctl_judge_int__(line)
#define impdrv_cmnctl_judge_int__(line) impdrv_cmnctl_judge_int_ut_##line
#define impdrv_cmnctl_judge_int_ut_2081 impdrv_cmnctl_judge_int_stub

#define impdrv_cmnctl_get_init_param impdrv_cmnctl_get_init_param_(__LINE__)
#define impdrv_cmnctl_get_init_param_(line) impdrv_cmnctl_get_init_param__(line)
#define impdrv_cmnctl_get_init_param__(line) impdrv_cmnctl_get_init_param_ut_##line
#define impdrv_cmnctl_get_init_param_ut_635 impdrv_cmnctl_get_init_param_stub

#define impdrv_cmnctl_get_dsp_func impdrv_cmnctl_get_dsp_func_(__LINE__)
#define impdrv_cmnctl_get_dsp_func_(line) impdrv_cmnctl_get_dsp_func__(line)
#define impdrv_cmnctl_get_dsp_func__(line) impdrv_cmnctl_get_dsp_func_ut_##line
#define impdrv_cmnctl_get_dsp_func_ut_640 impdrv_cmnctl_get_dsp_func_stub

#define impdrv_genctl_chk_state_init impdrv_genctl_chk_state_init_(__LINE__)
#define impdrv_genctl_chk_state_init_(line) impdrv_genctl_chk_state_init__(line)
#define impdrv_genctl_chk_state_init__(line) impdrv_genctl_chk_state_init_ut_##line
#define impdrv_genctl_chk_state_init_ut_98 impdrv_genctl_chk_state_init
#define impdrv_genctl_chk_state_init_ut_538 impdrv_genctl_chk_state_init_stub
#define impdrv_genctl_chk_state_init_ut_1525 impdrv_genctl_chk_state_init
#define impdrv_genctl_chk_state_init_ut_2261 impdrv_genctl_chk_state_init

#include "r_impdrv_genctl.c"

