/* impdrv_cmnctl_reg_find_resource */
#define impdrv_cmnctl_reg_find_resource impdrv_cmnctl_reg_find_resource_(__LINE__)
#define impdrv_cmnctl_reg_find_resource_(line) impdrv_cmnctl_reg_find_resource__(line)
#define impdrv_cmnctl_reg_find_resource__(line) impdrv_cmnctl_reg_find_resource_ut_##line
/* V3H2 */
// #define impdrv_cmnctl_reg_find_resource_ut_319 impdrv_cmnctl_reg_find_resource
// #define impdrv_cmnctl_reg_find_resource_ut_659 impdrv_cmnctl_reg_find_resource
// #define impdrv_cmnctl_reg_find_resource_ut_715 impdrv_cmnctl_reg_find_resource
// #define impdrv_cmnctl_reg_find_resource_ut_803 impdrv_cmnctl_reg_find_resource
// #define impdrv_cmnctl_reg_find_resource_ut_895 impdrv_cmnctl_reg_find_resource_stub
// #define impdrv_cmnctl_reg_find_resource_ut_1218 impdrv_cmnctl_reg_find_resource
// /* V3H1, V3M2 */
// #define impdrv_cmnctl_reg_find_resource_ut_314 impdrv_cmnctl_reg_find_resource
// #define impdrv_cmnctl_reg_find_resource_ut_629 impdrv_cmnctl_reg_find_resource
// #define impdrv_cmnctl_reg_find_resource_ut_685 impdrv_cmnctl_reg_find_resource
// #define impdrv_cmnctl_reg_find_resource_ut_773 impdrv_cmnctl_reg_find_resource
// #define impdrv_cmnctl_reg_find_resource_ut_865 impdrv_cmnctl_reg_find_resource_stub
// #define impdrv_cmnctl_reg_find_resource_ut_1188 impdrv_cmnctl_reg_find_resource
/* V4H */
#define impdrv_cmnctl_reg_find_resource_ut_370 impdrv_cmnctl_reg_find_resource
#define impdrv_cmnctl_reg_find_resource_ut_656 impdrv_cmnctl_reg_find_resource
#define impdrv_cmnctl_reg_find_resource_ut_712 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_800 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_892 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_969 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_1297 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_1426 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_1547 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_1613 impdrv_cmnctl_reg_find_resource
/* V4H2,V4M */
#define impdrv_cmnctl_reg_find_resource_ut_370 impdrv_cmnctl_reg_find_resource
#define impdrv_cmnctl_reg_find_resource_ut_656 impdrv_cmnctl_reg_find_resource
// #define impdrv_cmnctl_reg_find_resource_ut_712 impdrv_cmnctl_reg_find_resource
// #define impdrv_cmnctl_reg_find_resource_ut_800 impdrv_cmnctl_reg_find_resource
#define impdrv_cmnctl_reg_find_resource_ut_892 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_1247 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_1376 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_1497 impdrv_cmnctl_reg_find_resource_stub
#define impdrv_cmnctl_reg_find_resource_ut_1563 impdrv_cmnctl_reg_find_resource

/* impdrv_cmnctl_get_io_imptop */
#define impdrv_cmnctl_get_io_imptop impdrv_cmnctl_get_io_imptop_(__LINE__)
#define impdrv_cmnctl_get_io_imptop_(line) impdrv_cmnctl_get_io_imptop__(line)
#define impdrv_cmnctl_get_io_imptop__(line) impdrv_cmnctl_get_io_imptop_ut_##line
/* V3H2 */
// #define impdrv_cmnctl_get_io_imptop_ut_1116 impdrv_cmnctl_get_io_imptop_stub
// /* V3H1, V3M2 */
// #define impdrv_cmnctl_get_io_imptop_ut_1146 impdrv_cmnctl_get_io_imptop_stub
/* V4H */
#define impdrv_cmnctl_get_io_imptop_ut_1195 impdrv_cmnctl_get_io_imptop_stub
/* V4H2, V4M */
#define impdrv_cmnctl_get_io_imptop_ut_1143 impdrv_cmnctl_get_io_imptop_stub

/* impdrv_cmnctl_calc_checksum */
#define impdrv_cmnctl_calc_checksum impdrv_cmnctl_calc_checksum_(__LINE__)
#define impdrv_cmnctl_calc_checksum_(line) impdrv_cmnctl_calc_checksum__(line)
#define impdrv_cmnctl_calc_checksum__(line) impdrv_cmnctl_calc_checksum_ut_##line
/* V3H2 */
// #define impdrv_cmnctl_calc_checksum_ut_961 impdrv_cmnctl_calc_checksum_stub
// #define impdrv_cmnctl_calc_checksum_ut_988 impdrv_cmnctl_calc_checksum_stub
// /* V3H1, V3M2 */
// #define impdrv_cmnctl_calc_checksum_ut_931 impdrv_cmnctl_calc_checksum_stub
// #define impdrv_cmnctl_calc_checksum_ut_958 impdrv_cmnctl_calc_checksum_stub
/* V4H */
#define impdrv_cmnctl_calc_checksum_ut_1010 impdrv_cmnctl_calc_checksum_stub
#define impdrv_cmnctl_calc_checksum_ut_1037 impdrv_cmnctl_calc_checksum_stub
/* V4H2, V4M */
#define impdrv_cmnctl_calc_checksum_ut_958 impdrv_cmnctl_calc_checksum_stub
#define impdrv_cmnctl_calc_checksum_ut_985 impdrv_cmnctl_calc_checksum_stub

#include "r_impdrv_cmnctl_reg.c"
