/***********************************************************************************************************************
* Copyright [2023] Renesas Electronics Corporation and/or its licensors. All Rights Reserved.
*
* The contents of this file (the "contents") are proprietary and confidential to Renesas Electronics Corporation
* and/or its licensors ("Renesas") and subject to statutory and contractual protections.
*
* Unless otherwise expressly agreed in writing between Renesas and you: 1) you may not use, copy, modify, distribute,
* display, or perform the contents; 2) you may not use any name or mark of Renesas for advertising or publicity
* purposes or in connection with your use of the contents; 3) RENESAS MAKES NO WARRANTY OR REPRESENTATIONS ABOUT THE
* SUITABILITY OF THE CONTENTS FOR ANY PURPOSE; THE CONTENTS ARE PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
* WARRANTY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
* NON-INFRINGEMENT; AND 4) RENESAS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, OR CONSEQUENTIAL DAMAGES,
* INCLUDING DAMAGES RESULTING FROM LOSS OF USE, DATA, OR PROJECTS, WHETHER IN AN ACTION OF CONTRACT OR TORT, ARISING
* OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE CONTENTS. Third-party contents included in this file may
* be subject to different terms.
***********************************************************************************************************************/
/***********************************************************************************************************************
* File Name :    expected_perf_v3m.h
* Version :      3.0.0
* Product Name : OSAL
* Device(s) :    R-Car
* Description :  Header for the expected execution time on V3M2.0
***********************************************************************************************************************/
/***********************************************************************************************************************
 * History   Version   DD.MM.YYYY    Description
 *           3.0.0     24.05.2023    Newly create
***********************************************************************************************************************/
#ifndef OSAL_PERF_EXPECT_V3M_H_
#define OSAL_PERF_EXPECT_V3M_H_

#define USEC_TO_NSEC (1000U)

#if defined(TEST_PERF_LINUX_HIL) /* Linux HIL expected execution time value */

#define EXPECT_R_OSAL_Initialize                            625000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_Deinitialize                          50000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_GetVersion                            13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadCreate                          6250 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepUntilTimeStamp             12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepForTimePeriod              12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSelf                            50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadEqual                           38 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadInitializeThreadConfigSt        13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadJoin                            125 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexCreate                     175 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexDestroy                    88 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockUntilTimeStamp         63 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockForTimePeriod          63 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexTryLock                    50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexUnlock                     50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondCreate                      113 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondDestroy                     88 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitUntilTimeStamp          15000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitForTimePeriod           15000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondBroadcast                   50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondSignal                      50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMemoryBarrier                   25 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqCreate                              225 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqDelete                              163 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendUntilTimeStamp                  125 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendForTimePeriod                   125 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveUntilTimeStamp               125 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveForTimePeriod                125 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsFull                              63 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsEmpty                             63 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqGetConfig                           38 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReset                               88 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqInitializeMqConfigSt                13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeGetTimeStamp                 13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeCalculateTimeDifference      13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptGetNumOfIrqChannels          38 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptRegisterIsr                  6250 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptUnregisterIsr                6250 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptEnableIsr                    100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptDisableIsr                   63 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptIsISRContext                 25 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptSetIsrPriority               50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfDevices                     6250 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceList                       6250 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceOpen                          6250 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceClose                         475 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead8                               13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead16                              13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead32                              13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead64                              13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite8                              13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite16                             13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite32                             13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite64                             13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead8                          13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead16                         13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead32                         13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead64                         13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite8                         13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite16                        13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite32                        13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite64                        13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusIdFromDeviceName           238 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusName                       63 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusNameList                   50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceAxiBusId                   238 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForAxiBusName         413 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForAxiBusName           463 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceHdl          200 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceHdl            250 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceName         175 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceName           225 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetRequiredState                    125 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetRequiredState                    50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmWaitForState                        88 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetState                            63 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPolicy                           125 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetPolicy                           50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetResetState                       75 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetResetState                       63 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetLowestIntermediatePowerState     50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPostClock                        138 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpen                             250000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrClose                            87500 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrAlloc                            6250 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDealloc                          50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConfig                        38 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfig                 13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMmngrConfigSt          13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrRegisterMonitor                  38 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetCpuPtr                        38 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConstCpuPtr                   38 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrFlush                            50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInvalidate                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetHwAddr                        50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetSize                          13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrCheckBuffer                      150 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugMmngrPrint                  113 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugBufferPrint                 50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryBufferObj        13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryManagerObj       13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfigFromRegionIdx    13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpenFromRegionIdx                250000 * USEC_TO_NSEC

#elif defined(TEST_PERF_QNX) /* QNX expected execution time value */

#define EXPECT_R_OSAL_Initialize                            41347 * USEC_TO_NSEC
#define EXPECT_R_OSAL_Deinitialize                          53028 * USEC_TO_NSEC
#define EXPECT_R_OSAL_GetVersion                            13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadCreate                          48 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepUntilTimeStamp             13750 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepForTimePeriod              13750 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSelf                            19 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadEqual                           13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadInitializeThreadConfigSt        13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadJoin                            19 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexCreate                     18 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexDestroy                    14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockUntilTimeStamp         14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockForTimePeriod          14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexTryLock                    14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexUnlock                     14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondCreate                      17 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondDestroy                     14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitUntilTimeStamp          12659 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitForTimePeriod           12197 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondBroadcast                   19 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondSignal                      19 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMemoryBarrier                   14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqCreate                              20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqDelete                              14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendUntilTimeStamp                  15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendForTimePeriod                   14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveUntilTimeStamp               14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveForTimePeriod                14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsFull                              14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsEmpty                             14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqGetConfig                           14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReset                               15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqInitializeMqConfigSt                13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeGetTimeStamp                 14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeCalculateTimeDifference      13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptGetNumOfIrqChannels          13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptRegisterIsr                  30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptUnregisterIsr                14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptEnableIsr                    18 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptDisableIsr                   17 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptIsISRContext                 14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptSetIsrPriority               17 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfDevices                     3360 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceList                       3358 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceOpen                          17 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceClose                         15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead8                               13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead16                              13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead32                              13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead64                              13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite8                              13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite16                             13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite32                             13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite64                             13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead8                          13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead16                         13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead32                         13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead64                         13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite8                         13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite16                        13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite32                        13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite64                        13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusIdFromDeviceName           1572 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusName                       14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusNameList                   1595 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceAxiBusId                   1608 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForAxiBusName         1574 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForAxiBusName           1580 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceHdl          13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceHdl            1582 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceName         1562 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceName           1574 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetRequiredState                    55 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetRequiredState                    14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmWaitForState                        18 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetState                            24 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPolicy                           3425 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetPolicy                           14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetResetState                       27 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetResetState                       14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetLowestIntermediatePowerState     14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPostClock                        42 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpen                             12533 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrClose                            101020 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrAlloc                            72 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDealloc                          14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConfig                        14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfig                 13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMmngrConfigSt          13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrRegisterMonitor                  15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetCpuPtr                        14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConstCpuPtr                   14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrFlush                            15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInvalidate                       19 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetHwAddr                        14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetSize                          14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrCheckBuffer                      39 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugMmngrPrint                  124 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugBufferPrint                 37 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryBufferObj        13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryManagerObj       13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfigFromRegionIdx    12187 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpenFromRegionIdx                13 * USEC_TO_NSEC

#elif defined(TEST_PERF_ZEPHYR) /* Zephyr expected execution time value */

#define EXPECT_R_OSAL_Initialize                            23349 * USEC_TO_NSEC
#define EXPECT_R_OSAL_Deinitialize                          24742 * USEC_TO_NSEC
#define EXPECT_R_OSAL_GetVersion                            10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadCreate                          63 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepUntilTimeStamp             11000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepForTimePeriod              11000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSelf                            13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadEqual                           10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadInitializeThreadConfigSt        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadJoin                            16 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexCreate                     15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexDestroy                    11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockUntilTimeStamp         11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockForTimePeriod          11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexTryLock                    11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexUnlock                     11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondCreate                      14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondDestroy                     12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitUntilTimeStamp          7155 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitForTimePeriod           6914 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondBroadcast                   22 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondSignal                      22 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMemoryBarrier                   11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqCreate                              15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqDelete                              12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendUntilTimeStamp                  12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendForTimePeriod                   12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveUntilTimeStamp               12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveForTimePeriod                12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsFull                              12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsEmpty                             12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqGetConfig                           11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReset                               13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqInitializeMqConfigSt                10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeGetTimeStamp                 11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeCalculateTimeDifference      10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptGetNumOfIrqChannels          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptRegisterIsr                  31 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptUnregisterIsr                12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptEnableIsr                    19 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptDisableIsr                   15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptIsISRContext                 11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptSetIsrPriority               18 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfDevices                     1087 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceList                       1085 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceOpen                          15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceClose                         12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead8                               10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead16                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead32                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead64                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite8                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite16                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite32                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite64                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead8                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead16                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead32                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead64                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite8                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite16                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite32                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite64                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusIdFromDeviceName           670 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusName                       12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusNameList                   683 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceAxiBusId                   669 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForAxiBusName         111 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForAxiBusName           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceHdl          29 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceHdl            30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceName         1582 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceName           12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetRequiredState                    23 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetRequiredState                    12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmWaitForState                        12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetState                            49 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPolicy                           178882 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetPolicy                           91955 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetResetState                       86 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetResetState                       12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetLowestIntermediatePowerState     11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPostClock                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpen                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrClose                            11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrAlloc                            11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDealloc                          11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConfig                        14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfig                 16 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMmngrConfigSt          11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrRegisterMonitor                  11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetCpuPtr                        61 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConstCpuPtr                   220 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrFlush                            60 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInvalidate                       10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetHwAddr                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetSize                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrCheckBuffer                      679 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugMmngrPrint                  693 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugBufferPrint                 684 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryBufferObj        679 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryManagerObj       694 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfigFromRegionIdx    177408 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpenFromRegionIdx                10 * USEC_TO_NSEC

#elif defined(TEST_PERF_WINDOWS) /* Zephyr expected execution time value */

#define EXPECT_R_OSAL_Initialize                            500000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_Deinitialize                          40000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_GetVersion                            10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadCreate                          5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepUntilTimeStamp             12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepForTimePeriod              12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSelf                            40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadEqual                           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadInitializeThreadConfigSt        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadJoin                            100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexCreate                     140 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexDestroy                    70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockUntilTimeStamp         50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockForTimePeriod          50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexTryLock                    40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexUnlock                     40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondCreate                      90 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondDestroy                     70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitUntilTimeStamp          12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitForTimePeriod           12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondBroadcast                   40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondSignal                      40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMemoryBarrier                   20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqCreate                              180 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqDelete                              130 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendUntilTimeStamp                  100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendForTimePeriod                   100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveUntilTimeStamp               100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveForTimePeriod                100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsFull                              50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsEmpty                             50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqGetConfig                           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReset                               70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqInitializeMqConfigSt                10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeGetTimeStamp                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeCalculateTimeDifference      10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptGetNumOfIrqChannels          30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptRegisterIsr                  5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptUnregisterIsr                5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptEnableIsr                    80 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptDisableIsr                   50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptIsISRContext                 20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptSetIsrPriority               40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfDevices                     5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceList                       5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceOpen                          5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceClose                         380 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead8                               10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead16                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead32                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead64                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite8                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite16                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite32                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite64                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead8                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead16                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead32                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead64                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite8                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite16                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite32                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite64                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusIdFromDeviceName           190 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusName                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusNameList                   40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceAxiBusId                   190 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForAxiBusName         330 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForAxiBusName           370 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceHdl          160 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceHdl            200 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceName         140 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceName           180 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetRequiredState                    100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetRequiredState                    40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmWaitForState                        70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetState                            50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPolicy                           100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetPolicy                           40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetResetState                       60 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetResetState                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetLowestIntermediatePowerState     40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPostClock                        110 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpen                             200000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrClose                            70000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrAlloc                            5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDealloc                          40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConfig                        30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfig                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMmngrConfigSt          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrRegisterMonitor                  30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetCpuPtr                        30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConstCpuPtr                   30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrFlush                            40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInvalidate                       40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetHwAddr                        40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetSize                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrCheckBuffer                      120 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugMmngrPrint                  90 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugBufferPrint                 40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryBufferObj        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryManagerObj       10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfigFromRegionIdx    10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpenFromRegionIdx                200000 * USEC_TO_NSEC

#elif defined(TEST_PERF_LINUX_SIL) /* Linux SIL expected execution time value */

#define EXPECT_R_OSAL_Initialize                            500000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_Deinitialize                          40000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_GetVersion                            10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadCreate                          5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepUntilTimeStamp             12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepForTimePeriod              12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSelf                            40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadEqual                           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadInitializeThreadConfigSt        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadJoin                            100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexCreate                     140 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexDestroy                    70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockUntilTimeStamp         50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockForTimePeriod          50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexTryLock                    40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexUnlock                     40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondCreate                      90 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondDestroy                     70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitUntilTimeStamp          12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitForTimePeriod           12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondBroadcast                   40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondSignal                      40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMemoryBarrier                   20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqCreate                              180 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqDelete                              130 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendUntilTimeStamp                  100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendForTimePeriod                   100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveUntilTimeStamp               100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveForTimePeriod                100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsFull                              50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsEmpty                             50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqGetConfig                           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReset                               70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqInitializeMqConfigSt                10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeGetTimeStamp                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeCalculateTimeDifference      10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptGetNumOfIrqChannels          30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptRegisterIsr                  5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptUnregisterIsr                5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptEnableIsr                    80 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptDisableIsr                   50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptIsISRContext                 20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptSetIsrPriority               40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfDevices                     5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceList                       5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceOpen                          5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceClose                         380 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead8                               10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead16                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead32                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead64                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite8                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite16                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite32                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite64                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead8                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead16                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead32                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead64                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite8                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite16                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite32                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite64                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusIdFromDeviceName           190 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusName                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusNameList                   40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceAxiBusId                   190 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForAxiBusName         330 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForAxiBusName           370 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceHdl          160 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceHdl            200 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceName         140 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceName           180 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetRequiredState                    100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetRequiredState                    40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmWaitForState                        70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetState                            50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPolicy                           100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetPolicy                           40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetResetState                       60 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetResetState                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetLowestIntermediatePowerState     40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPostClock                        110 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpen                             200000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrClose                            70000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrAlloc                            5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDealloc                          40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConfig                        30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfig                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMmngrConfigSt          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrRegisterMonitor                  30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetCpuPtr                        30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConstCpuPtr                   30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrFlush                            40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInvalidate                       40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetHwAddr                        40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetSize                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrCheckBuffer                      120 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugMmngrPrint                  90 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugBufferPrint                 40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryBufferObj        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryManagerObj       10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfigFromRegionIdx    10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpenFromRegionIdx                200000 * USEC_TO_NSEC

#else
#error  Target is not supported
#endif

#endif