/***********************************************************************************************************************
* Copyright [2023] Renesas Electronics Corporation and/or its licensors. All Rights Reserved.
*
* The contents of this file (the "contents") are proprietary and confidential to Renesas Electronics Corporation
* and/or its licensors ("Renesas") and subject to statutory and contractual protections.
*
* Unless otherwise expressly agreed in writing between Renesas and you: 1) you may not use, copy, modify, distribute,
* display, or perform the contents; 2) you may not use any name or mark of Renesas for advertising or publicity
* purposes or in connection with your use of the contents; 3) RENESAS MAKES NO WARRANTY OR REPRESENTATIONS ABOUT THE
* SUITABILITY OF THE CONTENTS FOR ANY PURPOSE; THE CONTENTS ARE PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
* WARRANTY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
* NON-INFRINGEMENT; AND 4) RENESAS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, OR CONSEQUENTIAL DAMAGES,
* INCLUDING DAMAGES RESULTING FROM LOSS OF USE, DATA, OR PROJECTS, WHETHER IN AN ACTION OF CONTRACT OR TORT, ARISING
* OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE CONTENTS. Third-party contents included in this file may
* be subject to different terms.
***********************************************************************************************************************/
/***********************************************************************************************************************
* File Name :    expected_perf_v3h.h
* Version :      3.0.0
* Product Name : OSAL
* Device(s) :    R-Car
* Description :  Header for the expected execution time on V3Hx
***********************************************************************************************************************/
/***********************************************************************************************************************
 * History   Version   DD.MM.YYYY    Description
 *           3.0.0     24.05.2023    Newly create
***********************************************************************************************************************/
#ifndef OSAL_PERF_EXPECT_V3H_H_
#define OSAL_PERF_EXPECT_V3H_H_

#define USEC_TO_NSEC (1000U)

#if defined(TEST_PERF_LINUX_HIL) /* Linux HIL expected execution time value */

#define EXPECT_R_OSAL_Initialize                            500000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_Deinitialize                          40000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_GetVersion                            10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadCreate                          5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepUntilTimeStamp             12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepForTimePeriod              12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSelf                            40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadEqual                           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadInitializeThreadConfigSt        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadJoin                            100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexCreate                     140 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexDestroy                    70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockUntilTimeStamp         50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockForTimePeriod          50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexTryLock                    40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexUnlock                     40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondCreate                      90 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondDestroy                     70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitUntilTimeStamp          12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitForTimePeriod           12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondBroadcast                   40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondSignal                      40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMemoryBarrier                   20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqCreate                              180 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqDelete                              130 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendUntilTimeStamp                  100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendForTimePeriod                   100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveUntilTimeStamp               100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveForTimePeriod                100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsFull                              50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsEmpty                             50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqGetConfig                           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReset                               70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqInitializeMqConfigSt                10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeGetTimeStamp                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeCalculateTimeDifference      10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptGetNumOfIrqChannels          30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptRegisterIsr                  5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptUnregisterIsr                5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptEnableIsr                    80 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptDisableIsr                   50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptIsISRContext                 20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptSetIsrPriority               40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfDevices                     5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceList                       5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceOpen                          5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceClose                         380 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead8                               10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead16                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead32                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead64                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite8                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite16                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite32                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite64                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead8                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead16                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead32                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead64                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite8                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite16                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite32                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite64                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusIdFromDeviceName           190 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusName                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusNameList                   40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceAxiBusId                   190 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForAxiBusName         330 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForAxiBusName           370 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceHdl          160 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceHdl            200 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceName         140 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceName           180 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetRequiredState                    100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetRequiredState                    40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmWaitForState                        70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetState                            50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPolicy                           100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetPolicy                           40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetResetState                       60 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetResetState                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetLowestIntermediatePowerState     40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPostClock                        110 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpen                             200000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrClose                            70000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrAlloc                            5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDealloc                          40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConfig                        30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfig                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMmngrConfigSt          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrRegisterMonitor                  30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetCpuPtr                        30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConstCpuPtr                   30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrFlush                            40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInvalidate                       40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetHwAddr                        40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetSize                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrCheckBuffer                      120 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugMmngrPrint                  90 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugBufferPrint                 40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryBufferObj        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryManagerObj       10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfigFromRegionIdx    10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpenFromRegionIdx                200000 * USEC_TO_NSEC

#elif defined(TEST_PERF_QNX) /* QNX expected execution time value */

#define EXPECT_R_OSAL_Initialize                            33077 * USEC_TO_NSEC
#define EXPECT_R_OSAL_Deinitialize                          42422 * USEC_TO_NSEC
#define EXPECT_R_OSAL_GetVersion                            10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadCreate                          38 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepUntilTimeStamp             11000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepForTimePeriod              11000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSelf                            15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadEqual                           10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadInitializeThreadConfigSt        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadJoin                            15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexCreate                     14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexDestroy                    11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockUntilTimeStamp         11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockForTimePeriod          11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexTryLock                    11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexUnlock                     11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondCreate                      13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondDestroy                     11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitUntilTimeStamp          10127 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitForTimePeriod           9757 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondBroadcast                   15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondSignal                      15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMemoryBarrier                   11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqCreate                              16 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqDelete                              11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendUntilTimeStamp                  12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendForTimePeriod                   11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveUntilTimeStamp               11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveForTimePeriod                11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsFull                              11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsEmpty                             11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqGetConfig                           11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReset                               12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqInitializeMqConfigSt                10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeGetTimeStamp                 11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeCalculateTimeDifference      10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptGetNumOfIrqChannels          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptRegisterIsr                  24 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptUnregisterIsr                11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptEnableIsr                    14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptDisableIsr                   13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptIsISRContext                 11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptSetIsrPriority               13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfDevices                     2688 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceList                       2686 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceOpen                          13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceClose                         12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead8                               10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead16                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead32                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead64                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite8                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite16                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite32                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite64                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead8                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead16                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead32                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead64                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite8                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite16                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite32                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite64                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusIdFromDeviceName           1257 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusName                       11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusNameList                   1276 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceAxiBusId                   1286 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForAxiBusName         1259 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForAxiBusName           1264 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceHdl          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceHdl            1265 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceName         1249 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceName           1259 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetRequiredState                    44 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetRequiredState                    11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmWaitForState                        14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetState                            19 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPolicy                           2740 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetPolicy                           11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetResetState                       21 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetResetState                       11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetLowestIntermediatePowerState     11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPostClock                        33 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpen                             10026 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrClose                            80816 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrAlloc                            57 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDealloc                          11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConfig                        11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfig                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMmngrConfigSt          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrRegisterMonitor                  12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetCpuPtr                        11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConstCpuPtr                   11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrFlush                            12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInvalidate                       15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetHwAddr                        11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetSize                          11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrCheckBuffer                      31 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugMmngrPrint                  99 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugBufferPrint                 29 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryBufferObj        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryManagerObj       10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfigFromRegionIdx    9749 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpenFromRegionIdx                10 * USEC_TO_NSEC

#elif defined(TEST_PERF_ZEPHYR) /* Zephyr expected execution time value */

#define EXPECT_R_OSAL_Initialize                            23349 * USEC_TO_NSEC
#define EXPECT_R_OSAL_Deinitialize                          24742 * USEC_TO_NSEC
#define EXPECT_R_OSAL_GetVersion                            10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadCreate                          63 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepUntilTimeStamp             11000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepForTimePeriod              11000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSelf                            13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadEqual                           10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadInitializeThreadConfigSt        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadJoin                            16 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexCreate                     15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexDestroy                    11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockUntilTimeStamp         11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockForTimePeriod          11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexTryLock                    11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexUnlock                     11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondCreate                      14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondDestroy                     12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitUntilTimeStamp          7155 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitForTimePeriod           6914 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondBroadcast                   22 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondSignal                      22 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMemoryBarrier                   11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqCreate                              15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqDelete                              12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendUntilTimeStamp                  12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendForTimePeriod                   12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveUntilTimeStamp               12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveForTimePeriod                12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsFull                              12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsEmpty                             12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqGetConfig                           11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReset                               13 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqInitializeMqConfigSt                10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeGetTimeStamp                 11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeCalculateTimeDifference      10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptGetNumOfIrqChannels          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptRegisterIsr                  31 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptUnregisterIsr                12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptEnableIsr                    19 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptDisableIsr                   15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptIsISRContext                 11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptSetIsrPriority               18 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfDevices                     1087 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceList                       1085 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceOpen                          15 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceClose                         12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead8                               10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead16                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead32                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead64                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite8                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite16                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite32                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite64                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead8                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead16                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead32                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead64                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite8                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite16                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite32                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite64                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusIdFromDeviceName           670 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusName                       12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusNameList                   683 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceAxiBusId                   669 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForAxiBusName         111 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForAxiBusName           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceHdl          29 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceHdl            30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceName         1582 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceName           12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetRequiredState                    23 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetRequiredState                    12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmWaitForState                        12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetState                            49 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPolicy                           178882 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetPolicy                           91955 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetResetState                       86 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetResetState                       12 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetLowestIntermediatePowerState     11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPostClock                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpen                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrClose                            11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrAlloc                            11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDealloc                          11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConfig                        14 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfig                 16 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMmngrConfigSt          11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrRegisterMonitor                  11 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetCpuPtr                        61 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConstCpuPtr                   220 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrFlush                            60 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInvalidate                       10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetHwAddr                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetSize                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrCheckBuffer                      679 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugMmngrPrint                  693 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugBufferPrint                 684 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryBufferObj        679 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryManagerObj       694 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfigFromRegionIdx    177408 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpenFromRegionIdx                10 * USEC_TO_NSEC

#elif defined(TEST_PERF_WINDOWS) /* Zephyr expected execution time value */

#define EXPECT_R_OSAL_Initialize                            500000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_Deinitialize                          40000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_GetVersion                            10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadCreate                          5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepUntilTimeStamp             12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepForTimePeriod              12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSelf                            40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadEqual                           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadInitializeThreadConfigSt        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadJoin                            100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexCreate                     140 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexDestroy                    70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockUntilTimeStamp         50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockForTimePeriod          50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexTryLock                    40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexUnlock                     40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondCreate                      90 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondDestroy                     70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitUntilTimeStamp          12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitForTimePeriod           12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondBroadcast                   40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondSignal                      40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMemoryBarrier                   20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqCreate                              180 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqDelete                              130 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendUntilTimeStamp                  100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendForTimePeriod                   100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveUntilTimeStamp               100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveForTimePeriod                100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsFull                              50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsEmpty                             50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqGetConfig                           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReset                               70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqInitializeMqConfigSt                10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeGetTimeStamp                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeCalculateTimeDifference      10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptGetNumOfIrqChannels          30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptRegisterIsr                  5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptUnregisterIsr                5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptEnableIsr                    80 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptDisableIsr                   50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptIsISRContext                 20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptSetIsrPriority               40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfDevices                     5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceList                       5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceOpen                          5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceClose                         380 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead8                               10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead16                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead32                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead64                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite8                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite16                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite32                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite64                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead8                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead16                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead32                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead64                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite8                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite16                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite32                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite64                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusIdFromDeviceName           190 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusName                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusNameList                   40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceAxiBusId                   190 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForAxiBusName         330 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForAxiBusName           370 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceHdl          160 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceHdl            200 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceName         140 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceName           180 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetRequiredState                    100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetRequiredState                    40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmWaitForState                        70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetState                            50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPolicy                           100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetPolicy                           40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetResetState                       60 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetResetState                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetLowestIntermediatePowerState     40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPostClock                        110 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpen                             200000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrClose                            70000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrAlloc                            5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDealloc                          40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConfig                        30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfig                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMmngrConfigSt          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrRegisterMonitor                  30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetCpuPtr                        30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConstCpuPtr                   30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrFlush                            40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInvalidate                       40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetHwAddr                        40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetSize                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrCheckBuffer                      120 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugMmngrPrint                  90 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugBufferPrint                 40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryBufferObj        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryManagerObj       10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfigFromRegionIdx    10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpenFromRegionIdx                200000 * USEC_TO_NSEC

#elif defined(TEST_PERF_LINUX_SIL) /* Linux SIL expected execution time value */

#define EXPECT_R_OSAL_Initialize                            500000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_Deinitialize                          40000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_GetVersion                            10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadCreate                          5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepUntilTimeStamp             12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSleepForTimePeriod              12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadSelf                            40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadEqual                           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadInitializeThreadConfigSt        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThreadJoin                            100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexCreate                     140 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexDestroy                    70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockUntilTimeStamp         50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexLockForTimePeriod          50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexTryLock                    40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMutexUnlock                     40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondCreate                      90 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondDestroy                     70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitUntilTimeStamp          12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondWaitForTimePeriod           12000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondBroadcast                   40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncCondSignal                      40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ThsyncMemoryBarrier                   20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqCreate                              180 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqDelete                              130 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendUntilTimeStamp                  100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqSendForTimePeriod                   100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveUntilTimeStamp               100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReceiveForTimePeriod                100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsFull                              50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqIsEmpty                             50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqGetConfig                           30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqReset                               70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MqInitializeMqConfigSt                10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeGetTimeStamp                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_ClockTimeCalculateTimeDifference      10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptGetNumOfIrqChannels          30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptRegisterIsr                  5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptUnregisterIsr                5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptEnableIsr                    80 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptDisableIsr                   50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptIsISRContext                 20 * USEC_TO_NSEC
#define EXPECT_R_OSAL_InterruptSetIsrPriority               40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfDevices                     5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceList                       5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceOpen                          5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoDeviceClose                         380 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead8                               10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead16                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead32                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoRead64                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite8                              10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite16                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite32                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoWrite64                             10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead8                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead16                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead32                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockRead64                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite8                         10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite16                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite32                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoBlockWrite64                        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusIdFromDeviceName           190 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusName                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiBusNameList                   40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetDeviceAxiBusId                   190 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForAxiBusName         330 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForAxiBusName           370 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceHdl          160 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceHdl            200 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetNumOfAxiIdsForDeviceName         140 * USEC_TO_NSEC
#define EXPECT_R_OSAL_IoGetAxiIdListForDeviceName           180 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetRequiredState                    100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetRequiredState                    40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmWaitForState                        70 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetState                            50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPolicy                           100 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetPolicy                           40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetResetState                       60 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetResetState                       50 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmGetLowestIntermediatePowerState     40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_PmSetPostClock                        110 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpen                             200000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrClose                            70000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrAlloc                            5000 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDealloc                          40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConfig                        30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfig                 10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMmngrConfigSt          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrRegisterMonitor                  30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetCpuPtr                        30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetConstCpuPtr                   30 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrFlush                            40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInvalidate                       40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetHwAddr                        40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetSize                          10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrCheckBuffer                      120 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugMmngrPrint                  90 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrDebugBufferPrint                 40 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryBufferObj        10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrInitializeMemoryManagerObj       10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrGetOsalMaxConfigFromRegionIdx    10 * USEC_TO_NSEC
#define EXPECT_R_OSAL_MmngrOpenFromRegionIdx                200000 * USEC_TO_NSEC

#else
#error  Target is not supported
#endif

#endif