ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include ../../../prodroot_pkt.mk

LIBS = drvrS netdrvrS drvr smmu

NAME = devnp-rswitch

USEFILE=$(PROJECT_ROOT)/$(NAME).use

define PINFO
PINFO DESCRIPTION=Renesas R-Car RSwitch Network driver
endef

ifneq ($(QNX_ALLOW_WERROR), 0)
CCFLAGS += -Werror
endif
#CCFLAGS +=	-Wunused-function -Wno-unused-function -Wunused-variable -Wno-unused-variable

EXTRA_INCVPATH+= $(EXTRA_INCVPATH_$(SECTION)) \
	         $(PRODUCT_ROOT)/../../install/usr/include


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

